/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v17.0
processor: MCXA166
package_id: MCXA166VLH
mcu_data: ksdk2_0
processor_version: 0.2412.20
external_user_signals:
  properties: [I/O Supply, Default, ISP, ANALOG, ALT0, ALT1, ALT2, ALT3, ALT4, ALT5, ALT6, ALT7, ALT8, ALT9, ALT10, ALT11, ALT12, VDD, Pad type, 'Motor Control Function ',
    Remark, Checked, NXP Comments]
  routingDetailsColumns: ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', Peripheral, Signal, Routed pin/signal, Direction]
  signals:
  - id: P1_8
    pin_connections: ['2']
    property_values: [VDD, DIS, I2C_SDA, '', P1_8, FREQME_CLK_IN0, LPUART1_RXD, LPI2C2_SDA, CT_INP8, CT0_MAT2, '', SmartDMA_PIO4, '', '', '', '', '', WUU0_IN10, HD+I3C,
      UART1_RXD, For main board comm., 'Yes', '']
  - id: P1_9
    pin_connections: ['3']
    property_values: [VDD, DIS, I2C_SCL, '', P1_9, FREQME_CLK_IN1, LPUART1_TXD, LPI2C2_SCL, CT_INP9, CT0_MAT3, '', SmartDMA_PIO5, '', '', '', '', '', '', HD, UART1_TXD,
      For main board comm., 'Yes', '']
  - id: P1_10
    pin_connections: ['4']
    property_values: [VDD, DIS, '', ADC1_A8, P1_10, '', LPUART1_RTS_B, LPI2C2_SDAS, CT2_MAT0, '', '', SmartDMA_PIO6, LPUART5_TXD, '', '', CAN0_TXD, '', '', SLOW,
      '', '', 'Yes', Rerouted GP_OUT_1 (24 -: 4)]
  - id: P1_11
    pin_connections: ['5']
    property_values: [VDD, DIS, '', ADC1_A9, P1_11, TRIG_OUT2, LPUART1_CTS_B, LPI2C2_SCLS, CT2_MAT1, '', '', SmartDMA_PIO7, LPUART5_RXD, '', '', CAN0_RXD, '', WUU0_IN11,
      SLOW, '', '', 'Yes', Rerouted GP_OUT_2 (26 -: 5)]
  - id: P1_12
    pin_connections: ['6']
    property_values: [VDD, DIS, '', ADC1_A10, P1_12, '', LPI2C1_SDA, LPUART2_RXD, CT2_MAT2, '', '', SmartDMA_PIO8, LPUART5_CTS_B, '', '', '', '', WUU0_IN12, SLOW,
      GP_OUT_3, test output (GPIO/OUT), 'Yes', '']
  - id: P1_13
    pin_connections: ['7']
    property_values: [VDD, DIS, '', ADC1_A11, P1_13, TRIG_IN3, LPI2C1_SCL, LPUART2_TXD, CT2_MAT3, '', '', SmartDMA_PIO9, LPUART5_RTS_B, '', '', '', '', '', SLOW,
      ADC1_A11_AC, AC line voltage sampling(ADC), 'Yes', '']
  - id: P1_29
    pin_connections: ['8']
    property_values: [VDD, ALT1, '', '', P1_29, RESET_B, SPC_LPREQ, '', '', '', '', '', '', '', '', '', '', RESET_B, RST, MCU RESET, MCU RESET, 'Yes', '']
  - id: P1_30
    pin_connections: ['9']
    property_values: [VDD, DIS, '', XTAL48M, P1_30, TRIG_OUT3, '', LPI2C0_SDA, CT_INP16, '', '', '', '', '', '', '', '', '', HD+I3C, XTAL_1, opt. xtal input, 'Yes',
      XTAL]
  - id: P1_31
    pin_connections: ['10']
    property_values: [VDD, DIS, '', EXTAL48M, P1_31, TRIG_IN4, '', LPI2C0_SCL, CT_INP17, '', '', '', '', '', '', '', '', '', HD, XTAL_2, opt. xtal input, 'Yes', EXTAL]
  - id: VSS
    pin_connections: ['11']
    property_values: [VDD, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'Yes', '']
  - id: VDD_ANA
    pin_connections: ['12']
    property_values: [VDD, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'Yes', '']
  - id: VDD
    pin_connections: ['13']
    property_values: [VDD, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'Yes', '']
  - id: P2_0
    pin_connections: ['14']
    property_values: [VDD, DIS, '', ADC0_A0/OPAMP2_INP, P2_0, TRIG_IN6, LPUART0_RXD, LPUART4_CTS_B, CT_INP16, CT2_MAT0, '', SmartDMA_PIO24, '', '', '', '', '', WUU0_IN18,
      SLOW, P2_0_DRUM_UP, test output (GPIO/OUT), 'Yes', OPMAP2_INP_CURR_W]
  - id: P2_1
    pin_connections: ['15']
    property_values: [VDD, DIS, '', ADC1_A0/OPAMP2_INN, P2_1, TRIG_IN7, LPUART0_TXD, LPUART4_RTS_B, CT_INP17, CT2_MAT1, '', SmartDMA_PIO25, '', '', '', '', '', '',
      SLOW, ADC1_A0_CURR_W, Current ADC for W(ADC), 'Yes', OPMAP2_INN_CURR_W]
  - id: P2_2
    pin_connections: ['16']
    property_values: [VDD, DIS, UART_TXD, ADC0_A4/CMP0_IN0/DAC0_OUT/CMP1_INN4/CMP2_INN4, P2_2, TRIG_IN6, LPUART0_RTS_B, LPUART2_TXD, CT_INP12, CT2_MAT2, '', SmartDMA_PIO26,
      '', '', '', '', '', '', SLOW, GP_OUT_4, test output  (GPIO/OUT), 'Yes', '']
  - id: P2_3
    pin_connections: ['17']
    property_values: [VDD, DIS, UART_RXD, ADC0_A3/CMP1_IN0/ADC1_A4, P2_3, TRIG_IN7, LPUART0_CTS_B, LPUART2_RXD, CT_INP13, CT2_MAT3, '', SmartDMA_PIO27, '', '', '',
      '', '', WUU0_IN19, SLOW, '', '', 'Yes', Rerouted OVER_CURRENT_TRIP_INP (39 -: 17)]
  - id: P2_4
    pin_connections: ['18']
    property_values: [VDD, DIS, '', ADC0_A1/ADC2_A0/CMP2_IN0, P2_4, '', '', LPUART2_CTS_B, CT_INP14, CT1_MAT0, '', SmartDMA_PIO28, '', '', '', '', '', '', SLOW, '',
      '', 'Yes', Not used]
  - id: P2_5
    pin_connections: ['19']
    property_values: [VDD, DIS, '', ADC1_A1/ADC3_A0, P2_5, '', '', LPUART2_RTS_B, CT_INP15, CT1_MAT1, '', SmartDMA_PIO29, '', '', '', '', '', '', SLOW, '', '', 'Yes',
      Rerouted ADC0_A6_MCU_ANALOG_TEST (25 -: 19)]
  - id: P2_6
    pin_connections: ['20']
    property_values: [VDD, DIS, '', ADC1_A3/ADC2_A2/OPAMP2_OUT/CMP2_INP4, P2_6, TRIG_OUT4, LPSPI1_PCS1, LPUART4_RXD, CT_INP18, CT1_MAT2, '', SmartDMA_PIO30, '', '',
      '', '', '', '', SLOW, '', '', 'Yes', OPMAP2_OUT_CURR_W (ADC1_A3 / ADC2_A2 / CMP2_INP4)]
  - id: P2_7
    pin_connections: ['21']
    property_values: [VDD, DIS, '', VREFI/ADC0_A7/ADC1_A7/ADC2_A7/ADC3_A7, P2_7, TRIG_IN5, '', LPUART4_TXD, CT_INP19, CT1_MAT3, '', SmartDMA_PIO31, '', '', '', '',
      '', '', SLOW, VREF, 'ADC Vef Inp??', 'Yes', '']
  - id: P2_12
    pin_connections: ['22']
    property_values: [VDD, DIS, '', ADC0_A5/ADC2_A5/OPAMP0_INP, P2_12, '', LPSPI1_SCK, LPUART1_RXD, CT4_MAT0, CT0_MAT0, '', SmartDMA_PIO16, '', '', '', CAN0_RXD,
      '', WUU0_IN20, SLOW, GP_OUT_0, test output  (GPIO/OUT), 'Yes', OPMAP0_INP_CURR_U]
  - id: P2_13
    pin_connections: ['23']
    property_values: [VDD, DIS, '', ADC1_A5/ADC3_A5/OPAMP0_INN, P2_13, TRIG_IN8, LPSPI1_SDO, LPUART1_TXD, CT4_MAT1, CT0_MAT1, '', SmartDMA_PIO17, '', '', '', CAN0_TXD,
      '', '', SLOW, ADC1_A5_CURR_V, Current ADC for V(ADC), 'Yes', OPAMP0_INN_CURR_U]
  - id: P2_15
    pin_connections: ['24']
    property_values: [VDD, DIS, '', OPAMP0_OUT/ADC0_A2/CMP0_INP4, P2_15, TRIG_OUT4, LPSPI1_SDI, LPUART1_RTS_B, CT4_MAT3, CT0_MAT2, '', SmartDMA_PIO18, '', '', '',
      '', '', WUU0_IN21, SLOW, GP_OUT_1, test output  (GPIO/OUT), 'Yes', OPAMP0_OUT_CURR_U (ADC0_A2 / CMP0_IN4)]
  - id: P2_16
    pin_connections: ['25']
    property_values: [VDD, DIS, '', ADC0_A6/ADC2_A4/OPAMP1_INP, P2_16, '', LPSPI1_SDI, LPUART1_RTS_B, CT3_MAT0, CT0_MAT2, '', SmartDMA_PIO19, '', '', '', '', '',
      '', SLOW, ADC0_A6_MCU_ANALOG_TEST, MCU analog test ADC inp (ADC), 'Yes', OPMAP1_INP_CURR_V]
  - id: P2_17
    pin_connections: ['26']
    property_values: [VDD, DIS, '', ADC1_A6/ADC3_A4/OPAMP1_INN, P2_17, TRIG_IN9, LPSPI1_PCS0, LPUART1_CTS_B, CT3_MAT1, CT0_MAT3, '', SmartDMA_PIO20, '', '', '', '',
      '', '', SLOW, GP_OUT_2, test output  (GPIO/OUT), 'Yes', OPMAP1_INN_CURR_V]
  - id: P2_19
    pin_connections: ['27']
    property_values: [VDD, DIS, '', ADC1_A2/OPAMP1_OUT/CMP1_INP4, P2_19, TRIG_OUT5, '', '', CT3_MAT3, '', '', SmartDMA_PIO21, '', '', '', '', '', '', SLOW, ADC1_A2_CURR_U,
      Current ADC for U (ADC), 'Yes', OPMAP1_OUT_CURR_V (ADC1_A2 / CMP1_IN4)]
  - id: VSS
    pin_connections: ['28']
    property_values: [VDD, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'Yes', '']
  - id: VDD
    pin_connections: ['29']
    property_values: [VDD, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'Yes', '']
  - id: P3_31
    pin_connections: ['30']
    property_values: [VDD, DIS, '', ADC1_A20, P3_31, TRIG_IN10, LPI2C3_SDAS, LPUART4_CTS_B, CT0_MAT3, '', '', PWM1_B0, '', '', SmartDMA_PIO31, '', '', LPTMR0_ALT2,
      SLOW+TAM, ADC1_A20_IPMTEMP, IPM temp reading ADC(ADC), 'Yes', '']
  - id: P3_30
    pin_connections: ['31']
    property_values: [VDD, DIS, '', ADC1_A21, P3_30, TRIG_OUT6, LPI2C3_SCLS, LPUART4_RTS_B, CT0_MAT2, '', '', PWM1_A0, '', '', SmartDMA_PIO30, '', '', '', SLOW, NTC_BYPASS_RLY,
      NTC bypass relay drive output (GPIO), 'Yes', '']
  - id: P3_29
    pin_connections: ['32']
    property_values: [VDD, ALT1, '', ADC1_A22, P3_29, ISPMODE_N, LPI2C3_HREQ, '', CT_INP3, CT3_MAT3, '', '', '', '', SmartDMA_PIO29, '', '', WUU0_IN27, SLOW+TAM,
      '', '', 'Yes', Not used]
  - id: P3_28
    pin_connections: ['33']
    property_values: [VDD, DIS, '', '', P3_28, TRIG_IN11, LPI2C3_SDA, LPUART4_RXD, CT_INP12, CT3_MAT2, '', PWM1_B3, '', '', SmartDMA_PIO28, '', '', WUU0_IN26, 5VTOL,
      UART4_RXD, General UART, 'Yes', '']
  - id: P3_27
    pin_connections: ['34']
    property_values: [VDD, DIS, '', '', P3_27, TRIG_OUT7, LPI2C3_SCL, LPUART4_TXD, CT_INP13, CT3_MAT1, '', PWM1_A3, '', '', SmartDMA_PIO27, '', '', WUU0_IN30, 5VTOL,
      UART4_TXD, General UART, 'Yes', '']
  - id: P3_15
    pin_connections: ['35']
    property_values: [VDD, DIS, '', ADC3_A17, P3_15, '', LPUART2_TXD, LPUART3_RTS_B, CT_INP7, PWM0_X3, '', PWM1_B1, '', '', SmartDMA_PIO15, '', '', '', SLOW, '',
      '', 'Yes', Not used]
  - id: P3_14
    pin_connections: ['36']
    property_values: [VDD, DIS, '', ADC3_A16, P3_14, '', LPUART2_RXD, LPUART3_CTS_B, CT_INP6, PWM0_X2, '', PWM1_A1, '', '', SmartDMA_PIO14, '', '', WUU0_IN25, SLOW,
      GP_INP_0, test input  (GPIO/INPUT), 'Yes', '']
  - id: P3_13
    pin_connections: ['37']
    property_values: [VDD, DIS, '', ADC3_A15, P3_13, '', LPUART2_CTS_B, LPUART3_RXD, CT1_MAT3, PWM0_X1, '', PWM1_B2, '', '', SmartDMA_PIO13, '', '', '', SLOW, GP_INP_1,
      test input  (GPIO/INPUT), 'Yes', '']
  - id: P3_12
    pin_connections: ['38']
    property_values: [VDD, DIS, '', ADC3_A14, P3_12, '', LPUART2_RTS_B, LPUART3_TXD, CT1_MAT2, PWM0_X0, '', PWM1_A2, '', '', SmartDMA_PIO12, '', '', '', SLOW, GP_INP_2,
      test input  (GPIO/INPUT), 'Yes', '']
  - id: P3_11
    pin_connections: ['39']
    property_values: [VDD, DIS, '', '', P3_11, TRIG_IN6, LPSPI1_PCS0, LPUART1_CTS_B, CT1_MAT1, PWM0_B2, '', '', LPUART5_RXD, '', SmartDMA_PIO11, '', '', WUU0_IN24,
      MED, OVER_CURRENT_TRIP_INP, over current trip input fast, 'Yes', Rerouted PWM_W_L (41 -: 39)]
  - id: P3_10
    pin_connections: ['40']
    property_values: [VDD, DIS, '', '', P3_10, TRIG_IN5, LPSPI1_SCK, LPUART1_RTS_B, CT1_MAT0, PWM0_A2, '', '', LPUART5_TXD, '', SmartDMA_PIO10, '', '', '', MED, OVER_VOLTAGE_TRIP_INP,
      over voltage trip input fast, 'Yes', Rerouted PWM_W_H (42 -: 40)]
  - id: P3_9
    pin_connections: ['41']
    property_values: [VDD, DIS, '', '', P3_9, TRIG_IN4, LPSPI1_SDI, LPUART1_TXD, CT_INP5, PWM0_B1, '', '', LPUART5_RTS_B, '', SmartDMA_PIO9, '', '', '', MED, PWM_W_L,
      'to IPM, W phase, low side driver (active high)', 'Yes', Rerouted to PWM_V_L (43 -: 41)]
  - id: P3_8
    pin_connections: ['42']
    property_values: [VDD, DIS, '', '', P3_8, TRIG_IN3, LPSPI1_SDO, LPUART1_RXD, CT_INP4, PWM0_A1, '', '', LPUART5_CTS_B, '', SmartDMA_PIO8, '', CLKOUT, WUU0_IN23,
      MED, PWM_W_H, 'to IPM, W phase, high side driver (active high)', 'Yes', Rerouted to PWM_V_H (44 -: 42)]
  - id: P3_7
    pin_connections: ['43']
    property_values: [VDD, DIS, '', ADC3_A13, P3_7, TRIG_IN2, LPSPI1_PCS2, LPUART3_CTS_B, CT4_MAT3, PWM0_B3, '', PWM1_B0, '', '', SmartDMA_PIO7, '', '', '', MED,
      PWM_V_L, 'to IPM, V phase, low side driver (active high)', 'Yes', Not used]
  - id: P3_6
    pin_connections: ['44']
    property_values: [VDD, DIS, '', ADC3_A12, P3_6, CLKOUT, LPSPI1_PCS3, LPUART3_RTS_B, CT4_MAT2, PWM0_A3, '', PWM1_A0, '', '', SmartDMA_PIO6, '', FREQME_CLK_OUT1,
      '', MED, PMW_V_H, 'to IPM, V phase, high side driver (active high)', 'Yes', Not used]
  - id: P3_1
    pin_connections: ['45']
    property_values: [VDD, DIS, '', '', P3_1, TRIG_IN1, '', LPUART3_TXD, CT_INP17, PWM0_B0, '', PWM1_X1, '', '', SmartDMA_PIO1, '', FREQME_CLK_OUT0, '', HD, PMW_U_L,
      'to IPM, U phase, low side driver (active high)', 'Yes', '']
  - id: P3_0
    pin_connections: ['46']
    property_values: [VDD, DIS, '', '', P3_0, TRIG_IN0, '', LPUART3_RXD, CT_INP16, PWM0_A0, '', PWM1_X0, '', '', SmartDMA_PIO0, '', '', WUU0_IN22, HD, PMW_U_H, 'to
        IPM,U phase, high side driver (active high)', 'Yes', '']
  - id: VSS
    pin_connections: ['47']
    property_values: [VDD, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'Yes', '']
  - id: VDD
    pin_connections: ['48']
    property_values: [VDD, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'Yes', '']
  - id: P0_0
    pin_connections: ['49']
    property_values: [VDD, ALT1, '', '', P0_0, TMS/SWDIO, LPUART0_RTS_B, LPSPI0_PCS0, CT_INP0, '', '', '', '', '', '', '', '', '', SLOW, SWDIO, debug/programming,
      'Yes', '']
  - id: P0_1
    pin_connections: ['50']
    property_values: [VDD, ALT1, '', '', P0_1, TCLK/SWCLK, LPUART0_CTS_B, LPSPI0_SDI, CT_INP1, '', '', '', '', '', '', '', '', '', SLOW, SWCLK, debug/programming,
      'Yes', '']
  - id: P0_2
    pin_connections: ['51']
    property_values: [VDD, ALT1, '', ADC2_A8, P0_2, TDO/SWO, LPUART0_RXD, LPSPI0_SCK, CT0_MAT0, UTICK_CAP0, '', '', '', '', '', '', '', '', SLOW, SWO, debug/programming,
      'Yes', '']
  - id: P0_3
    pin_connections: ['52']
    property_values: [VDD, ALT1, '', CMP1_IN1/ADC0_A14, P0_3, TDI, LPUART0_TXD, LPSPI0_SDO, CT0_MAT1, UTICK_CAP1, '', '', CMP0_OUT, '', '', '', '', '', SLOW, '',
      '', 'Yes', Not used]
  - id: P0_6
    pin_connections: ['53']
    property_values: [VDD, ALT1, ISPMODE_N, ADC0_A15, P0_6, ISPMODE_N, LPI2C0_HREQ, LPSPI0_PCS1, CT_INP2, '', '', SmartDMA_PIO2, CMP1_OUT, '', '', '', CLKOUT, '',
      SLOW, '??', '??', 'Yes', Not used]
  - id: P0_16
    pin_connections: ['54']
    property_values: [VDD, DIS, '', '', P0_16, '', LPI2C0_SDA, LPSPI0_PCS2, CT0_MAT0, UTICK_CAP2, '', SmartDMA_PIO6, '', '', '', '', '', WUU0_IN2, HD+I3C, '', '',
      'Yes', Rerouted P2_0_DRUM_UP (14 -: 54)]
  - id: P0_17
    pin_connections: ['55']
    property_values: [VDD, DIS, '', '', P0_17, '', LPI2C0_SCL, LPSPI0_PCS3, CT0_MAT1, UTICK_CAP3, '', SmartDMA_PIO7, '', '', '', '', '', '', HD, '', '', 'Yes', Rerouted
        GP_OUT_0 (22 -: 55)]
  - id: P1_0
    pin_connections: ['56']
    property_values: [VDD, DIS, SPI_SDO, ADC0_A16/CMP0_IN3, P1_0, TRIG_IN0, LPSPI0_SDO, LPI2C1_SDA, CT_INP4, CT0_MAT2, '', '', '', '', '', '', '', WUU0_IN6/LPTMR0_ALT3,
      MED+I2C, '', '', 'Yes', Rerouted OVER_VOLTAGE_TRIP_INP (40 -: 56)]
  - id: P1_1
    pin_connections: ['57']
    property_values: [VDD, DIS, SPI_SCK, ADC0_A17/CMP1_IN3, P1_1, TRIG_IN1, LPSPI0_SCK, LPI2C1_SCL, CT_INP5, CT0_MAT3, '', '', '', '', '', '', '', '', MED+I2C, GP_OUT_5,
      test output  (GPIO/OUT), 'Yes', '']
  - id: P1_2
    pin_connections: ['58']
    property_values: [VDD, DIS, SPI_SDI, ADC0_A18/CMP2_IN3, P1_2, TRIG_OUT0, LPSPI0_SDI, LPI2C1_SDAS, CT1_MAT0, CT_INP0, '', '', '', '', '', CAN0_TXD, '', '', MED,
      ADC0_A18_VBUS_DC_2, DC BUS voltage input-2 (ADC), 'Yes', '']
  - id: P1_3
    pin_connections: ['59']
    property_values: [VDD, DIS, SPI_PCS, ADC0_A19/CMP0_IN1, P1_3, TRIG_OUT1, LPSPI0_PCS0, LPI2C1_SCLS, CT1_MAT1, CT_INP1, '', '', '', '', '', CAN0_RXD, '', WUU0_IN7,
      MED, ADC0_A19_VBUS_DC_1, DC BUS voltage input-1 (ADC), 'Yes', '']
  - id: VDD
    pin_connections: ['60']
    property_values: [VDD, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'Yes', '']
  - id: VSS
    pin_connections: ['61']
    property_values: [VDD, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'Yes', '']
  - id: P1_4
    pin_connections: ['62']
    property_values: [VDD, DIS, '', ADC0_A20/CMP0_IN2, P1_4, FREQME_CLK_IN0, LPSPI0_PCS3, LPUART2_RXD, CT1_MAT2, '', '', SmartDMA_PIO0, '', '', '', '', '', WUU0_IN8,
      MED, ADC0_A20_BEMF_W, Motor W phase voltage  (ADC), 'Yes', BEMF_W]
  - id: P1_5
    pin_connections: ['63']
    property_values: [VDD, DIS, '', ADC0_A21/CMP1_IN2, P1_5, FREQME_CLK_IN1, LPSPI0_PCS2, LPUART2_TXD, CT1_MAT3, '', '', SmartDMA_PIO1, '', '', '', '', '', '', MED,
      ADC0_A21_BEMF_V, Motor V phase voltage  (ADC), 'Yes', BEMF_V]
  - id: P1_6
    pin_connections: ['64']
    property_values: [VDD, DIS, '', ADC0_A22, P1_6, TRIG_IN2, LPSPI0_PCS1, LPUART2_RTS_B, CT_INP6, CT4_MAT0, '', SmartDMA_PIO2, '', '', '', '', '', '', MED, ADC0_A22_BEMF_U,
      Motor U phase voltage  (ADC), 'Yes', BEMF_U]
  - id: P1_7
    pin_connections: ['1']
    property_values: [VDD, DIS, '', ADC0_A23, P1_7, TRIG_OUT2, '', LPUART2_CTS_B, CT_INP7, CT4_MAT1, '', SmartDMA_PIO3, '', '', '', '', '', WUU0_IN9, MED, '', '',
      'Yes', Not used]
pin_labels:
- {pin_num: '6', pin_signal: P1_12/WUU0_IN12/LPI2C1_SDA/LPUART2_RXD/CT2_MAT2/SmartDMA_PIO8/LPUART5_CTS_B/ADC1_A10, label: FB_HEATER, identifier: GP_OUT_3;FB_HEATER}
- {pin_num: '16', pin_signal: P2_2/TRIG_IN6/LPUART0_RTS_B/LPUART2_TXD/CT_INP12/CT2_MAT2/SmartDMA_PIO26/ADC0_A4/CMP0_IN0/DAC0_OUT, label: DAC_OUT, identifier: GP_OUT_4;DAC_OUT;DAC_OUT_CMP0N;DAC_OUT_CMP0P;DAC_OUT_ADC0A4}
- {pin_num: '24', pin_signal: P2_15/WUU0_IN21/TRIG_OUT4/LPSPI1_SDI/LPUART1_RTS_B/CT4_MAT3/CT0_MAT2/SmartDMA_PIO18/OPAMP0_OUT/ADC0_A2, label: OPAMP0_OUT_CURR_U, identifier: GP_OUT_1;CURR_U;OPAMP0_OUT_CURR_U;ADC0_A2_CURR_U}
- {pin_num: '26', pin_signal: P2_17/TRIG_IN9/LPSPI1_PCS0/LPUART1_CTS_B/CT3_MAT1/CT0_MAT3/SmartDMA_PIO20/ADC1_A6/ADC3_A4/OPAMP1_INN, label: OPAMP1_INN_CURR_V, identifier: GP_OUT_2;OPAMP1_OUT_CURR_V;OPAMP1_INN_CURR_V;ADC1_A6_CURR_V;ADC3_A4_CURR_V}
- {pin_num: '31', pin_signal: P3_30/TRIG_OUT6/LPI2C3_SCLS/LPUART4_RTS_B/CT0_MAT2/PWM1_A0/SmartDMA_PIO30/ADC1_A21, label: PUMP_SET, identifier: NTC_BYPASS_RLY;PUMP_SEP;PUMP_SET}
- {pin_num: '36', pin_signal: P3_14/WUU0_IN25/LPUART2_RXD/LPUART3_CTS_B/CT_INP6/PWM0_X2/PWM1_A1/SmartDMA_PIO14/ADC3_A16, label: PILOT_EV_H2O, identifier: GP_INP_0;PILOT_EV_H2O}
- {pin_num: '37', pin_signal: P3_13/LPUART2_CTS_B/LPUART3_RXD/CT1_MAT3/PWM0_X1/PWM1_B2/SmartDMA_PIO13/ADC3_A15, label: PILOT_EV_DISP, identifier: GP_INP_1;PILOT_EV_DISP}
- {pin_num: '38', pin_signal: P3_12/LPUART2_RTS_B/LPUART3_TXD/CT1_MAT2/PWM0_X0/PWM1_A2/SmartDMA_PIO12/ADC3_A14, label: PILOT_EV_REGEN, identifier: GP_INP_2;PILOT_EV_REGEN}
- {pin_num: '39', pin_signal: P3_11/WUU0_IN24/TRIG_IN6/LPSPI1_PCS0/LPUART1_CTS_B/CT1_MAT1/PWM0_B2/LPUART5_RXD/SmartDMA_PIO11, label: PWM_W_L, identifier: PWM_W_L}
- {pin_num: '40', pin_signal: P3_10/TRIG_IN5/LPSPI1_SCK/LPUART1_RTS_B/CT1_MAT0/PWM0_A2/LPUART5_TXD/SmartDMA_PIO10, label: PWM_W_H, identifier: PWM_W_H}
- {pin_num: '41', pin_signal: P3_9/TRIG_IN4/LPSPI1_SDI/LPUART1_TXD/CT_INP5/PWM0_B1/LPUART5_RTS_B/SmartDMA_PIO9, label: PWM_V_L, identifier: PWM_V_L}
- {pin_num: '42', pin_signal: P3_8/WUU0_IN23/TRIG_IN3/LPSPI1_SDO/LPUART1_RXD/CT_INP4/PWM0_A1/LPUART5_CTS_B/SmartDMA_PIO8/CLKOUT, label: PWM_V_H, identifier: PWM_V_H}
- {pin_num: '45', pin_signal: P3_1/TRIG_IN1/LPUART3_TXD/CT_INP17/PWM0_B0/PWM1_X1/SmartDMA_PIO1/FREQME_CLK_OUT0, label: PMW_U_L, identifier: PMW_U_L}
- {pin_num: '46', pin_signal: P3_0/WUU0_IN22/TRIG_IN0/LPUART3_RXD/CT_INP16/PWM0_A0/PWM1_X0/SmartDMA_PIO0, label: PMW_U_H, identifier: PMW_U_H}
- {pin_num: '54', pin_signal: P0_16/WUU0_IN2/LPI2C0_SDA/LPSPI0_PCS2/CT0_MAT0/UTICK_CAP2/SmartDMA_PIO6, label: ZC_IN, identifier: DRUM_UP;ZC_IN}
- {pin_num: '55', pin_signal: P0_17/LPI2C0_SCL/LPSPI0_PCS3/CT0_MAT1/UTICK_CAP3/SmartDMA_PIO7, label: PILOT_GND_REL_HEAT, identifier: GP_OUT_0;PILOT_GND_REL_HEAT}
- {pin_num: '57', pin_signal: P1_1/TRIG_IN1/LPSPI0_SCK/LPI2C1_SCL/CT_INP5/CT0_MAT3/ADC0_A17/CMP1_IN3, label: GP_OUT_5, identifier: GP_OUT_5}
- {pin_num: '27', pin_signal: P2_19/TRIG_OUT5/CT3_MAT3/SmartDMA_PIO21/ADC1_A2/OPAMP1_OUT, label: OPAMP1_OUT_CURR_V, identifier: MP1_OUT_CURR_V;ADC1_A2_CURR_V;OPAMP1_OUT_CURR_V}
- {pin_num: '25', pin_signal: P2_16/LPSPI1_SDI/LPUART1_RTS_B/CT3_MAT0/CT0_MAT2/SmartDMA_PIO19/ADC0_A6/ADC2_A4/OPAMP1_INP, label: OPAMP1_INP_GNDV, identifier: OPAMP1_INP_CURR_V;ADC0_CURR_V;ADC2_CURR_V;ADC0_A6_CURR_V;ADC2_A4_CURR_V;OPAMP1_INP_GNDV}
- {pin_num: '14', pin_signal: P2_0/WUU0_IN18/TRIG_IN6/LPUART0_RXD/LPUART4_CTS_B/CT_INP16/CT2_MAT0/SmartDMA_PIO24/ADC0_A0/OPAMP2_INP, label: OPAMP2_INP_GNDW, identifier: OPAMP2_INP_CURR_W;ADC0_A0_CURR_W;OPAMP2_INP_GNDW;ADC0_A0_GNDW}
- {pin_num: '15', pin_signal: P2_1/TRIG_IN7/LPUART0_TXD/LPUART4_RTS_B/CT_INP17/CT2_MAT1/SmartDMA_PIO25/ADC1_A0/OPAMP2_INN, label: OPAMP2_INN_CURR_W, identifier: OPAMP2_INN_CURR_W;ADC1_CURR_W;ADC1_A0_CURR_W}
- {pin_num: '20', pin_signal: P2_6/TRIG_OUT4/LPSPI1_PCS1/LPUART4_RXD/CT_INP18/CT1_MAT2/SmartDMA_PIO30/ADC1_A3/ADC2_A2/OPAMP2_OUT, label: OPAMP2_OUT_CURR_W, identifier: OPAMP2_OUT_CURR_W;ADC2_A2_CURR_W;ADC1_A3_CURR_W}
- {pin_num: '4', pin_signal: P1_10/LPUART1_RTS_B/LPI2C2_SDAS/CT2_MAT0/SmartDMA_PIO6/LPUART5_TXD/CAN0_TXD/ADC1_A8, label: GP_OUT_1, identifier: GP_OUT_1}
- {pin_num: '5', pin_signal: P1_11/WUU0_IN11/TRIG_OUT2/LPUART1_CTS_B/LPI2C2_SCLS/CT2_MAT1/SmartDMA_PIO7/LPUART5_RXD/CAN0_RXD/ADC1_A9, label: FB_DIVER, identifier: GP_OUT_2;FB_DIVER}
- {pin_num: '2', pin_signal: P1_8/WUU0_IN10/FREQME_CLK_IN0/LPUART1_RXD/LPI2C2_SDA/CT_INP8/CT0_MAT2/SmartDMA_PIO4, label: COMM_MAIN_RX, identifier: COMM_MAIN_RX}
- {pin_num: '3', pin_signal: P1_9/FREQME_CLK_IN1/LPUART1_TXD/LPI2C2_SCL/CT_INP9/CT0_MAT3/SmartDMA_PIO5, label: FB_HEATER, identifier: COMM_MAIN_TX;FB_HEATER}
- {pin_num: '7', pin_signal: P1_13/TRIG_IN3/LPI2C1_SCL/LPUART2_TXD/CT2_MAT3/SmartDMA_PIO9/LPUART5_RTS_B/ADC1_A11, label: ADC1_AC_?LINE, identifier: AC_LINE;ADC1_AC_LINE;ADC1_A11_AC_LINE}
- {pin_num: '8', pin_signal: P1_29/RESET_B/SPC_LPREQ, label: RESET, identifier: RESET}
- {pin_num: '50', pin_signal: P0_1/TCLK/SWCLK/LPUART0_CTS_B/LPSPI0_SDI/CT_INP1, label: TCK_SWCLK, identifier: SWD_SWCLK;TCK_SWCLK}
- {pin_num: '62', pin_signal: P1_4/WUU0_IN8/FREQME_CLK_IN0/LPSPI0_PCS3/LPUART2_RXD/CT1_MAT2/SmartDMA_PIO0/ADC0_A20/CMP0_IN2, label: ADC0_A20_BEMF_W, identifier: ADC0_A20_BEMF_W;CMP0_IN2P_BEMF_W;CMP0_IN2N_BEMF_W}
- {pin_num: '63', pin_signal: P1_5/FREQME_CLK_IN1/LPSPI0_PCS2/LPUART2_TXD/CT1_MAT3/SmartDMA_PIO1/ADC0_A21/CMP1_IN2, label: ADC0_A21_BEMF_V, identifier: ADC0_A21_BEMF_V;CMP0_IN2N_BEMF_V;CMP1_IN2P_BEMF_V;CMP1_IN2N_BEMF_V}
- {pin_num: '64', pin_signal: P1_6/TRIG_IN2/LPSPI0_PCS1/LPUART2_RTS_B/CT_INP6/CT4_MAT0/SmartDMA_PIO2/ADC0_A22, label: ADC0_A22_BEMF_U, identifier: ADC0_A22_BEMF_V;ADC0_A22_BEMF_U}
- {pin_num: '58', pin_signal: P1_2/TRIG_OUT0/LPSPI0_SDI/LPI2C1_SDAS/CT1_MAT0/CT_INP0/CAN0_TXD/ADC0_A18/CMP2_IN3, label: ADC0_A18_VBUS_DC_2, identifier: ADC0_A18_VBUS_DC_2;CMP2_IN3_VBUS_DC_2;CMP2_IN3N_VBUS_DC_2;CMP2_IN3P_VBUS_DC_2}
- {pin_num: '59', pin_signal: P1_3/WUU0_IN7/TRIG_OUT1/LPSPI0_PCS0/LPI2C1_SCLS/CT1_MAT1/CT_INP1/CAN0_RXD/ADC0_A19/CMP0_IN1, label: ADC0_A18_VBUS_DC_1, identifier: ADC0_A18_VBUS_DC_2;ADC0_A18_VBUS_DC_1;CMP0_IN1P_VBUS_DC_1;CMP0_IN1N_VBUS_DC_1}
- {pin_num: '49', pin_signal: P0_0/TMS/SWDIO/LPUART0_RTS_B/LPSPI0_PCS0/CT_INP0, label: TMS_SWDIO, identifier: SWDIO;TMS_SWDIO}
- {pin_num: '51', pin_signal: P0_2/TDO/SWO/LPUART0_RXD/LPSPI0_SCK/CT0_MAT0/UTICK_CAP0/ADC2_A8, label: TDO_SWO, identifier: SWO;TDO_SWO}
- {pin_num: '17', pin_signal: P2_3/WUU0_IN19/TRIG_IN7/LPUART0_CTS_B/LPUART2_RXD/CT_INP13/CT2_MAT3/SmartDMA_PIO27/ADC0_A3/CMP1_IN0/ADC1_A4, label: IN_12V_DS, identifier: PWM0FAULT0_OVER_CURRENT_TRIP_INP;PWM0FAULT0_OVER_CURRENT_TRIP;PWM0FAULT0_OVER_CURRENT_TRIP_INMUX;IN_12VDS;IN_12V_DS}
- {pin_num: '56', pin_signal: P1_0/WUU0_IN6/LPTMR0_ALT3/TRIG_IN0/LPSPI0_SDO/LPI2C1_SDA/CT_INP4/CT0_MAT2/ADC0_A16/CMP0_IN3, label: PILOT_GND_SWITCH_REL, identifier: PWM0FAULT0_OVER_VOLTAGE_TRIP;PWM0FAULT0_OVER_VOLTAGE_TRIP_INMUX;PILOT_GND_SWITCH_REL}
- {pin_num: '30', pin_signal: P3_31/LPTMR0_ALT2/TRIG_IN10/LPI2C3_SDAS/LPUART4_CTS_B/CT0_MAT3/PWM1_B0/SmartDMA_PIO31/ADC1_A20, label: ADC1_IPMTEMP, identifier: ADC1_A20_IPMTEMP;ADC1_A28_IPMTEMP}
- {pin_num: '33', pin_signal: P3_28/WUU0_IN26/TRIG_IN11/LPI2C3_SDA/LPUART4_RXD/CT_INP12/CT3_MAT2/PWM1_B3/SmartDMA_PIO28, label: GEN_UART4_RX, identifier: GEN_UART4_RX}
- {pin_num: '34', pin_signal: P3_27/WUU0_IN30/TRIG_OUT7/LPI2C3_SCL/LPUART4_TXD/CT_INP13/CT3_MAT1/PWM1_A3/SmartDMA_PIO27, label: GEN_UART4_TX, identifier: GEN_UART4_TX}
- {pin_num: '9', pin_signal: P1_30/TRIG_OUT3/LPI2C0_SDA/CT_INP16/XTAL48M, label: OPT_XTAL_IN1, identifier: OPT_XTAL_IN1}
- {pin_num: '10', pin_signal: P1_31/TRIG_IN4/LPI2C0_SCL/CT_INP17/EXTAL48M, label: OPT_XTAL_IN2, identifier: OPT_XTAL_IN2}
- {pin_num: '19', pin_signal: P2_5/LPUART2_RTS_B/CT_INP15/CT1_MAT1/SmartDMA_PIO29/ADC1_A1/ADC3_A0, label: PILOT_FAIL_TST_BULK, identifier: ADC1_A1_MCU_ANALOG_TEST;ADC3_A0_MCU_ANALOG_TEST;PIL_FAIL_TST_BULK;PILOT_FAIL_TST_BULK}
- {pin_num: '21', pin_signal: P2_7/TRIG_IN5/LPUART4_TXD/CT_INP19/CT1_MAT3/SmartDMA_PIO31/VREFI/ADC1_A7/ADC3_A7/ADC0_A7/ADC2_A7, label: ADC_VREF_IN, identifier: ADC0_VREF_IN;ADC2_VREF_IN;ADC3_VREF_IN;ADC1_VREF_IN;CMP0_VREF_IN;CMP1_VREF_IN;ADC2_A7_VREF_IN;ADC3_A7_VREF_IN;ADC0_A7_VREF_IN;ADC1_A7_VREF_IN}
- {pin_num: '22', pin_signal: P2_12/WUU0_IN20/LPSPI1_SCK/LPUART1_RXD/CT4_MAT0/CT0_MAT0/SmartDMA_PIO16/CAN0_RXD/ADC0_A5/ADC2_A5/OPAMP0_INP, label: OPAMP0_INP_GNDU,
  identifier: ADC0_A5_INP_CURR_U;OPAMP0_INP;OPAMP0_INP_CURR_U;ADC2_A5_INP_CURR_U;OPAMP0_INP_GNDU}
- {pin_num: '23', pin_signal: P2_13/TRIG_IN8/LPSPI1_SDO/LPUART1_TXD/CT4_MAT1/CT0_MAT1/SmartDMA_PIO17/CAN0_TXD/ADC1_A5/ADC3_A5/OPAMP0_INN, label: OPAMP0_CURR_U_N,
  identifier: ADC1_A5_CURR_U_EXT;ADC3_A5_CURR_U_EXT;OPAMP0_INN;CURR_U_N;OPAMP0_CURR_U_N}
- {pin_num: '11', pin_signal: VSS/VSSA/VREFL, label: MC_GND}
- {pin_num: '12', pin_signal: VREFH/VDD_ANA, label: 3V3}
- {pin_num: '13', pin_signal: VDD13, label: MC_3V3}
- {pin_num: '35', pin_signal: P3_15/LPUART2_TXD/LPUART3_RTS_B/CT_INP7/PWM0_X3/PWM1_B1/SmartDMA_PIO15/ADC3_A17, label: PILOT_DIVER, identifier: PILOT_DIVER}
- {pin_num: '43', pin_signal: P3_7/TRIG_IN2/LPSPI1_PCS2/LPUART3_CTS_B/CT4_MAT3/PWM0_B3/PWM1_B0/SmartDMA_PIO7/ADC3_A13, label: PILOT_SYN_MOTOR, identifier: PILOT_SYN_MOTOR}
- {pin_num: '52', pin_signal: P0_3/TDI/LPUART0_TXD/LPSPI0_SDO/CT0_MAT1/UTICK_CAP1/CMP0_OUT/CMP1_IN1/ADC0_A14, label: TDI, identifier: TDI}
- {pin_num: '53', pin_signal: P0_6/ISPMODE_N/LPI2C0_HREQ/LPSPI0_PCS1/CT_INP2/SmartDMA_PIO2/CMP1_OUT/CLKOUT/ADC0_A15, label: MEAS_3V3, identifier: MEAS_3V3}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_port.h"
#include "fsl_gpio.h"
#include "fsl_inputmux.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', prefix: PIN_, coreID: cm33_core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '15', peripheral: ADC1, signal: 'A, 0', pin_signal: P2_1/TRIG_IN7/LPUART0_TXD/LPUART4_RTS_B/CT_INP17/CT2_MAT1/SmartDMA_PIO25/ADC1_A0/OPAMP2_INN, identifier: ADC1_A0_CURR_W}
  - {pin_num: '15', peripheral: OPAMP2, signal: 'op_inn, 0', pin_signal: P2_1/TRIG_IN7/LPUART0_TXD/LPUART4_RTS_B/CT_INP17/CT2_MAT1/SmartDMA_PIO25/ADC1_A0/OPAMP2_INN,
    identifier: OPAMP2_INN_CURR_W}
  - {pin_num: '16', peripheral: DAC0, signal: OUT, pin_signal: P2_2/TRIG_IN6/LPUART0_RTS_B/LPUART2_TXD/CT_INP12/CT2_MAT2/SmartDMA_PIO26/ADC0_A4/CMP0_IN0/DAC0_OUT,
    identifier: DAC_OUT}
  - {pin_num: '21', peripheral: ADC0, signal: VREFI, pin_signal: P2_7/TRIG_IN5/LPUART4_TXD/CT_INP19/CT1_MAT3/SmartDMA_PIO31/VREFI/ADC1_A7/ADC3_A7/ADC0_A7/ADC2_A7,
    identifier: ADC0_VREF_IN}
  - {pin_num: '21', peripheral: ADC2, signal: VREFI, pin_signal: P2_7/TRIG_IN5/LPUART4_TXD/CT_INP19/CT1_MAT3/SmartDMA_PIO31/VREFI/ADC1_A7/ADC3_A7/ADC0_A7/ADC2_A7,
    identifier: ADC2_VREF_IN}
  - {pin_num: '21', peripheral: ADC3, signal: VREFI, pin_signal: P2_7/TRIG_IN5/LPUART4_TXD/CT_INP19/CT1_MAT3/SmartDMA_PIO31/VREFI/ADC1_A7/ADC3_A7/ADC0_A7/ADC2_A7,
    identifier: ADC3_VREF_IN}
  - {pin_num: '21', peripheral: ADC1, signal: VREFI, pin_signal: P2_7/TRIG_IN5/LPUART4_TXD/CT_INP19/CT1_MAT3/SmartDMA_PIO31/VREFI/ADC1_A7/ADC3_A7/ADC0_A7/ADC2_A7,
    identifier: ADC1_VREF_IN}
  - {pin_num: '21', peripheral: CMP0, signal: DAC_8bit_VREFH2, pin_signal: P2_7/TRIG_IN5/LPUART4_TXD/CT_INP19/CT1_MAT3/SmartDMA_PIO31/VREFI/ADC1_A7/ADC3_A7/ADC0_A7/ADC2_A7,
    identifier: CMP0_VREF_IN}
  - {pin_num: '21', peripheral: CMP1, signal: DAC_8bit_VREFH2, pin_signal: P2_7/TRIG_IN5/LPUART4_TXD/CT_INP19/CT1_MAT3/SmartDMA_PIO31/VREFI/ADC1_A7/ADC3_A7/ADC0_A7/ADC2_A7,
    identifier: CMP1_VREF_IN}
  - {pin_num: '21', peripheral: ADC2, signal: 'A, 7', pin_signal: P2_7/TRIG_IN5/LPUART4_TXD/CT_INP19/CT1_MAT3/SmartDMA_PIO31/VREFI/ADC1_A7/ADC3_A7/ADC0_A7/ADC2_A7,
    identifier: ADC2_A7_VREF_IN}
  - {pin_num: '21', peripheral: ADC3, signal: 'A, 7', pin_signal: P2_7/TRIG_IN5/LPUART4_TXD/CT_INP19/CT1_MAT3/SmartDMA_PIO31/VREFI/ADC1_A7/ADC3_A7/ADC0_A7/ADC2_A7,
    identifier: ADC3_A7_VREF_IN}
  - {pin_num: '21', peripheral: ADC0, signal: 'A, 7', pin_signal: P2_7/TRIG_IN5/LPUART4_TXD/CT_INP19/CT1_MAT3/SmartDMA_PIO31/VREFI/ADC1_A7/ADC3_A7/ADC0_A7/ADC2_A7,
    identifier: ADC0_A7_VREF_IN}
  - {pin_num: '21', peripheral: ADC1, signal: 'A, 7', pin_signal: P2_7/TRIG_IN5/LPUART4_TXD/CT_INP19/CT1_MAT3/SmartDMA_PIO31/VREFI/ADC1_A7/ADC3_A7/ADC0_A7/ADC2_A7,
    identifier: ADC1_A7_VREF_IN}
  - {pin_num: '23', peripheral: OPAMP0, signal: 'op_inn, 0', pin_signal: P2_13/TRIG_IN8/LPSPI1_SDO/LPUART1_TXD/CT4_MAT1/CT0_MAT1/SmartDMA_PIO17/CAN0_TXD/ADC1_A5/ADC3_A5/OPAMP0_INN,
    identifier: OPAMP0_CURR_U_N}
  - {pin_num: '25', peripheral: OPAMP1, signal: 'op_inp, 0', pin_signal: P2_16/LPSPI1_SDI/LPUART1_RTS_B/CT3_MAT0/CT0_MAT2/SmartDMA_PIO19/ADC0_A6/ADC2_A4/OPAMP1_INP,
    identifier: OPAMP1_INP_GNDV}
  - {pin_num: '30', peripheral: ADC1, signal: 'A, 20', pin_signal: P3_31/LPTMR0_ALT2/TRIG_IN10/LPI2C3_SDAS/LPUART4_CTS_B/CT0_MAT3/PWM1_B0/SmartDMA_PIO31/ADC1_A20,
    identifier: ADC1_A20_IPMTEMP}
  - {pin_num: '30', peripheral: ADC1, signal: 'A, 28', pin_signal: P3_31/LPTMR0_ALT2/TRIG_IN10/LPI2C3_SDAS/LPUART4_CTS_B/CT0_MAT3/PWM1_B0/SmartDMA_PIO31/ADC1_A20,
    identifier: ADC1_A28_IPMTEMP}
  - {pin_num: '31', peripheral: GPIO3, signal: 'GPIO, 30', pin_signal: P3_30/TRIG_OUT6/LPI2C3_SCLS/LPUART4_RTS_B/CT0_MAT2/PWM1_A0/SmartDMA_PIO30/ADC1_A21, identifier: PUMP_SET,
    direction: OUTPUT}
  - {pin_num: '33', peripheral: LPUART4, signal: RX, pin_signal: P3_28/WUU0_IN26/TRIG_IN11/LPI2C3_SDA/LPUART4_RXD/CT_INP12/CT3_MAT2/PWM1_B3/SmartDMA_PIO28}
  - {pin_num: '34', peripheral: LPUART4, signal: TX, pin_signal: P3_27/WUU0_IN30/TRIG_OUT7/LPI2C3_SCL/LPUART4_TXD/CT_INP13/CT3_MAT1/PWM1_A3/SmartDMA_PIO27}
  - {pin_num: '36', peripheral: GPIO3, signal: 'GPIO, 14', pin_signal: P3_14/WUU0_IN25/LPUART2_RXD/LPUART3_CTS_B/CT_INP6/PWM0_X2/PWM1_A1/SmartDMA_PIO14/ADC3_A16,
    identifier: PILOT_EV_H2O, direction: OUTPUT}
  - {pin_num: '37', peripheral: GPIO3, signal: 'GPIO, 13', pin_signal: P3_13/LPUART2_CTS_B/LPUART3_RXD/CT1_MAT3/PWM0_X1/PWM1_B2/SmartDMA_PIO13/ADC3_A15, identifier: PILOT_EV_DISP,
    direction: OUTPUT}
  - {pin_num: '38', peripheral: GPIO3, signal: 'GPIO, 12', pin_signal: P3_12/LPUART2_RTS_B/LPUART3_TXD/CT1_MAT2/PWM0_X0/PWM1_A2/SmartDMA_PIO12/ADC3_A14, identifier: PILOT_EV_REGEN,
    direction: OUTPUT}
  - {pin_num: '41', peripheral: FlexPWM0, signal: 'B, 1', pin_signal: P3_9/TRIG_IN4/LPSPI1_SDI/LPUART1_TXD/CT_INP5/PWM0_B1/LPUART5_RTS_B/SmartDMA_PIO9, direction: OUTPUT}
  - {pin_num: '42', peripheral: FlexPWM0, signal: 'A, 1', pin_signal: P3_8/WUU0_IN23/TRIG_IN3/LPSPI1_SDO/LPUART1_RXD/CT_INP4/PWM0_A1/LPUART5_CTS_B/SmartDMA_PIO8/CLKOUT,
    direction: OUTPUT}
  - {pin_num: '45', peripheral: FlexPWM0, signal: 'B, 0', pin_signal: P3_1/TRIG_IN1/LPUART3_TXD/CT_INP17/PWM0_B0/PWM1_X1/SmartDMA_PIO1/FREQME_CLK_OUT0, direction: OUTPUT}
  - {pin_num: '46', peripheral: FlexPWM0, signal: 'A, 0', pin_signal: P3_0/WUU0_IN22/TRIG_IN0/LPUART3_RXD/CT_INP16/PWM0_A0/PWM1_X0/SmartDMA_PIO0, direction: OUTPUT}
  - {pin_num: '50', peripheral: SWD, signal: SWCLK, pin_signal: P0_1/TCLK/SWCLK/LPUART0_CTS_B/LPSPI0_SDI/CT_INP1, identifier: TCK_SWCLK}
  - {pin_num: '58', peripheral: ADC0, signal: 'A, 18', pin_signal: P1_2/TRIG_OUT0/LPSPI0_SDI/LPI2C1_SDAS/CT1_MAT0/CT_INP0/CAN0_TXD/ADC0_A18/CMP2_IN3, identifier: ADC0_A18_VBUS_DC_2}
  - {pin_num: '58', peripheral: CMP2, signal: 'IN, 3N', pin_signal: P1_2/TRIG_OUT0/LPSPI0_SDI/LPI2C1_SDAS/CT1_MAT0/CT_INP0/CAN0_TXD/ADC0_A18/CMP2_IN3, identifier: CMP2_IN3N_VBUS_DC_2}
  - {pin_num: '58', peripheral: CMP2, signal: 'IN, 3P', pin_signal: P1_2/TRIG_OUT0/LPSPI0_SDI/LPI2C1_SDAS/CT1_MAT0/CT_INP0/CAN0_TXD/ADC0_A18/CMP2_IN3, identifier: CMP2_IN3P_VBUS_DC_2}
  - {pin_num: '59', peripheral: ADC0, signal: 'A, 19', pin_signal: P1_3/WUU0_IN7/TRIG_OUT1/LPSPI0_PCS0/LPI2C1_SCLS/CT1_MAT1/CT_INP1/CAN0_RXD/ADC0_A19/CMP0_IN1, identifier: ADC0_A18_VBUS_DC_1}
  - {pin_num: '59', peripheral: CMP0, signal: 'IN, 1P', pin_signal: P1_3/WUU0_IN7/TRIG_OUT1/LPSPI0_PCS0/LPI2C1_SCLS/CT1_MAT1/CT_INP1/CAN0_RXD/ADC0_A19/CMP0_IN1, identifier: CMP0_IN1P_VBUS_DC_1}
  - {pin_num: '59', peripheral: CMP0, signal: 'IN, 1N', pin_signal: P1_3/WUU0_IN7/TRIG_OUT1/LPSPI0_PCS0/LPI2C1_SCLS/CT1_MAT1/CT_INP1/CAN0_RXD/ADC0_A19/CMP0_IN1, identifier: CMP0_IN1N_VBUS_DC_1}
  - {pin_num: '49', peripheral: SWD, signal: SWDIO, pin_signal: P0_0/TMS/SWDIO/LPUART0_RTS_B/LPSPI0_PCS0/CT_INP0, identifier: TMS_SWDIO}
  - {pin_num: '51', peripheral: SWD, signal: SWO, pin_signal: P0_2/TDO/SWO/LPUART0_RXD/LPSPI0_SCK/CT0_MAT0/UTICK_CAP0/ADC2_A8, identifier: TDO_SWO}
  - {pin_num: '10', peripheral: SCG0, signal: EXTAL, pin_signal: P1_31/TRIG_IN4/LPI2C0_SCL/CT_INP17/EXTAL48M}
  - {pin_num: '17', peripheral: GPIO2, signal: 'GPIO, 3', pin_signal: P2_3/WUU0_IN19/TRIG_IN7/LPUART0_CTS_B/LPUART2_RXD/CT_INP13/CT2_MAT3/SmartDMA_PIO27/ADC0_A3/CMP1_IN0/ADC1_A4,
    identifier: IN_12V_DS, direction: INPUT}
  - {pin_num: '56', peripheral: GPIO1, signal: 'GPIO, 0', pin_signal: P1_0/WUU0_IN6/LPTMR0_ALT3/TRIG_IN0/LPSPI0_SDO/LPI2C1_SDA/CT_INP4/CT0_MAT2/ADC0_A16/CMP0_IN3,
    identifier: PILOT_GND_SWITCH_REL, direction: OUTPUT}
  - {pin_num: '39', peripheral: FlexPWM0, signal: 'B, 2', pin_signal: P3_11/WUU0_IN24/TRIG_IN6/LPSPI1_PCS0/LPUART1_CTS_B/CT1_MAT1/PWM0_B2/LPUART5_RXD/SmartDMA_PIO11,
    direction: OUTPUT}
  - {pin_num: '40', peripheral: FlexPWM0, signal: 'A, 2', pin_signal: P3_10/TRIG_IN5/LPSPI1_SCK/LPUART1_RTS_B/CT1_MAT0/PWM0_A2/LPUART5_TXD/SmartDMA_PIO10, direction: OUTPUT}
  - {pin_num: '22', peripheral: OPAMP0, signal: 'op_inp, 0', pin_signal: P2_12/WUU0_IN20/LPSPI1_SCK/LPUART1_RXD/CT4_MAT0/CT0_MAT0/SmartDMA_PIO16/CAN0_RXD/ADC0_A5/ADC2_A5/OPAMP0_INP,
    identifier: OPAMP0_INP_GNDU}
  - {pin_num: '54', peripheral: GPIO0, signal: 'GPIO, 16', pin_signal: P0_16/WUU0_IN2/LPI2C0_SDA/LPSPI0_PCS2/CT0_MAT0/UTICK_CAP2/SmartDMA_PIO6, identifier: ZC_IN,
    direction: INPUT}
  - {pin_num: '55', peripheral: GPIO0, signal: 'GPIO, 17', pin_signal: P0_17/LPI2C0_SCL/LPSPI0_PCS3/CT0_MAT1/UTICK_CAP3/SmartDMA_PIO7, identifier: PILOT_GND_REL_HEAT,
    direction: OUTPUT}
  - {pin_num: '27', peripheral: OPAMP1, signal: OUT, pin_signal: P2_19/TRIG_OUT5/CT3_MAT3/SmartDMA_PIO21/ADC1_A2/OPAMP1_OUT, identifier: OPAMP1_OUT_CURR_V}
  - {pin_num: '24', peripheral: OPAMP0, signal: OUT, pin_signal: P2_15/WUU0_IN21/TRIG_OUT4/LPSPI1_SDI/LPUART1_RTS_B/CT4_MAT3/CT0_MAT2/SmartDMA_PIO18/OPAMP0_OUT/ADC0_A2,
    identifier: OPAMP0_OUT_CURR_U}
  - {pin_num: '26', peripheral: OPAMP1, signal: 'op_inn, 0', pin_signal: P2_17/TRIG_IN9/LPSPI1_PCS0/LPUART1_CTS_B/CT3_MAT1/CT0_MAT3/SmartDMA_PIO20/ADC1_A6/ADC3_A4/OPAMP1_INN,
    identifier: OPAMP1_INN_CURR_V}
  - {pin_num: '14', peripheral: OPAMP2, signal: 'op_inp, 0', pin_signal: P2_0/WUU0_IN18/TRIG_IN6/LPUART0_RXD/LPUART4_CTS_B/CT_INP16/CT2_MAT0/SmartDMA_PIO24/ADC0_A0/OPAMP2_INP,
    identifier: OPAMP2_INP_GNDW}
  - {pin_num: '14', peripheral: ADC0, signal: 'A, 0', pin_signal: P2_0/WUU0_IN18/TRIG_IN6/LPUART0_RXD/LPUART4_CTS_B/CT_INP16/CT2_MAT0/SmartDMA_PIO24/ADC0_A0/OPAMP2_INP,
    identifier: ADC0_A0_GNDW}
  - {pin_num: '20', peripheral: OPAMP2, signal: OUT, pin_signal: P2_6/TRIG_OUT4/LPSPI1_PCS1/LPUART4_RXD/CT_INP18/CT1_MAT2/SmartDMA_PIO30/ADC1_A3/ADC2_A2/OPAMP2_OUT,
    identifier: OPAMP2_OUT_CURR_W}
  - {pin_num: '20', peripheral: ADC2, signal: 'A, 2', pin_signal: P2_6/TRIG_OUT4/LPSPI1_PCS1/LPUART4_RXD/CT_INP18/CT1_MAT2/SmartDMA_PIO30/ADC1_A3/ADC2_A2/OPAMP2_OUT,
    identifier: ADC2_A2_CURR_W}
  - {pin_num: '20', peripheral: ADC1, signal: 'A, 3', pin_signal: P2_6/TRIG_OUT4/LPSPI1_PCS1/LPUART4_RXD/CT_INP18/CT1_MAT2/SmartDMA_PIO30/ADC1_A3/ADC2_A2/OPAMP2_OUT,
    identifier: ADC1_A3_CURR_W}
  - {pin_num: '9', peripheral: SCG0, signal: XTAL, pin_signal: P1_30/TRIG_OUT3/LPI2C0_SDA/CT_INP16/XTAL48M}
  - {pin_num: '19', peripheral: GPIO2, signal: 'GPIO, 5', pin_signal: P2_5/LPUART2_RTS_B/CT_INP15/CT1_MAT1/SmartDMA_PIO29/ADC1_A1/ADC3_A0, identifier: PILOT_FAIL_TST_BULK,
    direction: OUTPUT}
  - {pin_num: '5', peripheral: GPIO1, signal: 'GPIO, 11', pin_signal: P1_11/WUU0_IN11/TRIG_OUT2/LPUART1_CTS_B/LPI2C2_SCLS/CT2_MAT1/SmartDMA_PIO7/LPUART5_RXD/CAN0_RXD/ADC1_A9,
    identifier: FB_DIVER, direction: OUTPUT}
  - {pin_num: '8', peripheral: SYSCON, signal: RESET, pin_signal: P1_29/RESET_B/SPC_LPREQ}
  - {peripheral: CMP0, signal: 'IN, 4N', pin_signal: OPAMP3_OUT}
  - {peripheral: CMP0, signal: 'IN, 4P', pin_signal: OPAMP0_OUT}
  - {peripheral: CMP0, signal: 'IN, 7N', pin_signal: CMP0_DAC}
  - {peripheral: CMP0, signal: 'IN, 7P', pin_signal: CMP0_DAC}
  - {peripheral: CMP1, signal: 'IN, 4P', pin_signal: OPAMP1_OUT}
  - {peripheral: CMP1, signal: 'IN, 4N', pin_signal: DAC0_OUT}
  - {peripheral: CMP1, signal: 'IN, 7N', pin_signal: CMP1_DAC}
  - {peripheral: CMP1, signal: 'IN, 7P', pin_signal: CMP1_DAC}
  - {peripheral: CMP2, signal: 'IN, 4N', pin_signal: DAC0_OUT}
  - {peripheral: CMP2, signal: 'IN, 4P', pin_signal: OPAMP2_OUT}
  - {peripheral: CMP2, signal: 'IN, 7N', pin_signal: CMP2_DAC}
  - {peripheral: CMP2, signal: 'IN, 7P', pin_signal: CMP2_DAC}
  - {pin_num: '13', peripheral: SUPPLY, signal: VDD, pin_signal: VDD13}
  - {pin_num: '13', peripheral: CMP1, signal: DAC_8bit_VREFH1, pin_signal: VDD13}
  - {pin_num: '13', peripheral: CMP0, signal: DAC_8bit_VREFH1, pin_signal: VDD13}
  - {pin_num: '11', peripheral: SUPPLY, signal: VREFL, pin_signal: VSS/VSSA/VREFL}
  - {pin_num: '11', peripheral: SUPPLY, signal: VSS, pin_signal: VSS/VSSA/VREFL}
  - {pin_num: '11', peripheral: ADC3, signal: VREFL, pin_signal: VSS/VSSA/VREFL}
  - {pin_num: '11', peripheral: ADC3, signal: 'A, 24', pin_signal: VSS/VSSA/VREFL}
  - {pin_num: '11', peripheral: ADC2, signal: VREFL, pin_signal: VSS/VSSA/VREFL}
  - {pin_num: '11', peripheral: ADC2, signal: 'A, 24', pin_signal: VSS/VSSA/VREFL}
  - {pin_num: '11', peripheral: ADC1, signal: VREFL, pin_signal: VSS/VSSA/VREFL}
  - {pin_num: '11', peripheral: ADC1, signal: 'A, 24', pin_signal: VSS/VSSA/VREFL}
  - {pin_num: '11', peripheral: ADC0, signal: VREFL, pin_signal: VSS/VSSA/VREFL}
  - {pin_num: '11', peripheral: ADC0, signal: 'A, 24', pin_signal: VSS/VSSA/VREFL}
  - {pin_num: '12', peripheral: SUPPLY, signal: VREFH, pin_signal: VREFH/VDD_ANA}
  - {pin_num: '12', peripheral: SUPPLY, signal: VDD_ANA, pin_signal: VREFH/VDD_ANA}
  - {pin_num: '12', peripheral: ADC3, signal: VREFH, pin_signal: VREFH/VDD_ANA}
  - {pin_num: '12', peripheral: ADC3, signal: VDDA, pin_signal: VREFH/VDD_ANA}
  - {pin_num: '12', peripheral: DAC0, signal: VDDA, pin_signal: VREFH/VDD_ANA}
  - {pin_num: '12', peripheral: ADC2, signal: VREFH, pin_signal: VREFH/VDD_ANA}
  - {pin_num: '12', peripheral: ADC2, signal: VDDA, pin_signal: VREFH/VDD_ANA}
  - {pin_num: '12', peripheral: ADC1, signal: VREFH, pin_signal: VREFH/VDD_ANA}
  - {pin_num: '12', peripheral: ADC1, signal: VDDA, pin_signal: VREFH/VDD_ANA}
  - {pin_num: '12', peripheral: ADC0, signal: VREFH, pin_signal: VREFH/VDD_ANA}
  - {pin_num: '12', peripheral: ADC0, signal: VDDA, pin_signal: VREFH/VDD_ANA}
  - {pin_num: '48', peripheral: CMP0, signal: DAC_8bit_VREFH1, pin_signal: VDD48}
  - {pin_num: '48', peripheral: CMP1, signal: DAC_8bit_VREFH1, pin_signal: VDD48}
  - {pin_num: '48', peripheral: SUPPLY, signal: VDD, pin_signal: VDD48}
  - {pin_num: '47', peripheral: SUPPLY, signal: VSS, pin_signal: VSS47}
  - {pin_num: '28', peripheral: SUPPLY, signal: VSS, pin_signal: VSS28}
  - {pin_num: '29', peripheral: SUPPLY, signal: VDD, pin_signal: VDD29}
  - {pin_num: '29', peripheral: CMP1, signal: DAC_8bit_VREFH1, pin_signal: VDD29}
  - {pin_num: '29', peripheral: CMP0, signal: DAC_8bit_VREFH1, pin_signal: VDD29}
  - {pin_num: '61', peripheral: SUPPLY, signal: VSS, pin_signal: VSS61}
  - {pin_num: '60', peripheral: SUPPLY, signal: VDD, pin_signal: VDD60}
  - {pin_num: '60', peripheral: CMP1, signal: DAC_8bit_VREFH1, pin_signal: VDD60}
  - {pin_num: '60', peripheral: CMP0, signal: DAC_8bit_VREFH1, pin_signal: VDD60}
  - {pin_num: '3', peripheral: GPIO1, signal: 'GPIO, 9', pin_signal: P1_9/FREQME_CLK_IN1/LPUART1_TXD/LPI2C2_SCL/CT_INP9/CT0_MAT3/SmartDMA_PIO5, identifier: FB_HEATER,
    direction: INPUT}
  - {pin_num: '16', peripheral: CMP0, signal: 'IN, 0N', pin_signal: P2_2/TRIG_IN6/LPUART0_RTS_B/LPUART2_TXD/CT_INP12/CT2_MAT2/SmartDMA_PIO26/ADC0_A4/CMP0_IN0/DAC0_OUT,
    identifier: DAC_OUT_CMP0N}
  - {pin_num: '16', peripheral: CMP0, signal: 'IN, 0P', pin_signal: P2_2/TRIG_IN6/LPUART0_RTS_B/LPUART2_TXD/CT_INP12/CT2_MAT2/SmartDMA_PIO26/ADC0_A4/CMP0_IN0/DAC0_OUT,
    identifier: DAC_OUT_CMP0P}
  - {pin_num: '16', peripheral: ADC0, signal: 'A, 4', pin_signal: P2_2/TRIG_IN6/LPUART0_RTS_B/LPUART2_TXD/CT_INP12/CT2_MAT2/SmartDMA_PIO26/ADC0_A4/CMP0_IN0/DAC0_OUT,
    identifier: DAC_OUT_ADC0A4}
  - {pin_num: '35', peripheral: GPIO3, signal: 'GPIO, 15', pin_signal: P3_15/LPUART2_TXD/LPUART3_RTS_B/CT_INP7/PWM0_X3/PWM1_B1/SmartDMA_PIO15/ADC3_A17, direction: OUTPUT}
  - {pin_num: '43', peripheral: GPIO3, signal: 'GPIO, 7', pin_signal: P3_7/TRIG_IN2/LPSPI1_PCS2/LPUART3_CTS_B/CT4_MAT3/PWM0_B3/PWM1_B0/SmartDMA_PIO7/ADC3_A13, direction: OUTPUT}
  - {pin_num: '52', peripheral: JTAG, signal: TDI, pin_signal: P0_3/TDI/LPUART0_TXD/LPSPI0_SDO/CT0_MAT1/UTICK_CAP1/CMP0_OUT/CMP1_IN1/ADC0_A14}
  - {pin_num: '53', peripheral: ADC0, signal: 'A, 15', pin_signal: P0_6/ISPMODE_N/LPI2C0_HREQ/LPSPI0_PCS1/CT_INP2/SmartDMA_PIO2/CMP1_OUT/CLKOUT/ADC0_A15}
  - {peripheral: FlexPWM0, signal: 'PWM_FAULT_TRG_CH, 0', pin_signal: cmp0_out}
  - {peripheral: FlexPWM0, signal: 'PWM_FAULT_TRG_CH, 1', pin_signal: cmp1_out}
  - {peripheral: FlexPWM0, signal: 'PWM_FAULT_TRG_CH, 2', pin_signal: cmp2_out}
  - {peripheral: ADC0, signal: 'TRG_CH, 0', pin_signal: pwm0_sm0_mux_trig0}
  - {peripheral: ADC1, signal: 'TRG_CH, 0', pin_signal: pwm0_sm0_mux_trig0}
  - {peripheral: ADC2, signal: 'TRG_CH, 0', pin_signal: pwm0_sm0_mux_trig0}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void)
{
    /* GPIO0: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GateGPIO0);
    /* GPIO1: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GateGPIO1);
    /* GPIO2: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GateGPIO2);
    /* GPIO3: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GateGPIO3);
    /* INPUTMUX0: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GateINPUTMUX0);
    /* PORT0: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GatePORT0);
    /* PORT1: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GatePORT1);
    /* PORT2: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GatePORT2);
    /* PORT3: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GatePORT3);
    /* GPIO0 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kGPIO0_RST_SHIFT_RSTn);
    /* GPIO1 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kGPIO1_RST_SHIFT_RSTn);
    /* GPIO2 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kGPIO2_RST_SHIFT_RSTn);
    /* GPIO3 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kGPIO3_RST_SHIFT_RSTn);
    /* INPUTMUX0 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kINPUTMUX0_RST_SHIFT_RSTn);
    /* PORT0 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kPORT0_RST_SHIFT_RSTn);
    /* ADC0 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kADC0_RST_SHIFT_RSTn);
    /* PORT1 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kPORT1_RST_SHIFT_RSTn);
    /* CMP2 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kCMP2_RST_SHIFT_RSTn);
    /* PORT2 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kPORT2_RST_SHIFT_RSTn);
    /* ADC1 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kADC1_RST_SHIFT_RSTn);
    /* OPAMP0 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kOPAMP0_RST_SHIFT_RSTn);
    /* DAC0 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kDAC0_RST_SHIFT_RSTn);
    /* ADC2 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kADC2_RST_SHIFT_RSTn);
    /* ADC3 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kADC3_RST_SHIFT_RSTn);
    /* CMP1 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kCMP1_RST_SHIFT_RSTn);
    /* FLEXPWM0 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kFLEXPWM0_RST_SHIFT_RSTn);
    /* PORT3 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kPORT3_RST_SHIFT_RSTn);
    /* LPUART4 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kLPUART4_RST_SHIFT_RSTn);

    gpio_pin_config_t ZC_IN_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO0_16 (pin 54)  */
    GPIO_PinInit(PIN_ZC_IN_GPIO, PIN_ZC_IN_PIN, &ZC_IN_config);

    gpio_pin_config_t PILOT_GND_REL_HEAT_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO0_17 (pin 55)  */
    GPIO_PinInit(PIN_PILOT_GND_REL_HEAT_GPIO, PIN_PILOT_GND_REL_HEAT_PIN, &PILOT_GND_REL_HEAT_config);

    gpio_pin_config_t PILOT_GND_SWITCH_REL_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO1_0 (pin 56)  */
    GPIO_PinInit(PIN_PILOT_GND_SWITCH_REL_GPIO, PIN_PILOT_GND_SWITCH_REL_PIN, &PILOT_GND_SWITCH_REL_config);

    gpio_pin_config_t FB_HEATER_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO1_9 (pin 3)  */
    GPIO_PinInit(PIN_FB_HEATER_GPIO, PIN_FB_HEATER_PIN, &FB_HEATER_config);

    gpio_pin_config_t FB_DIVER_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO1_11 (pin 5)  */
    GPIO_PinInit(PIN_FB_DIVER_GPIO, PIN_FB_DIVER_PIN, &FB_DIVER_config);

    gpio_pin_config_t IN_12V_DS_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO2_3 (pin 17)  */
    GPIO_PinInit(PIN_IN_12V_DS_GPIO, PIN_IN_12V_DS_PIN, &IN_12V_DS_config);

    gpio_pin_config_t PILOT_FAIL_TST_BULK_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO2_5 (pin 19)  */
    GPIO_PinInit(PIN_PILOT_FAIL_TST_BULK_GPIO, PIN_PILOT_FAIL_TST_BULK_PIN, &PILOT_FAIL_TST_BULK_config);
/*
    gpio_pin_config_t PILOT_SYN_MOTOR_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };

    GPIO_PinInit(PIN_PILOT_SYN_MOTOR_GPIO, PIN_PILOT_SYN_MOTOR_PIN, &PILOT_SYN_MOTOR_config);
*/

/*
    gpio_pin_config_t PILOT_SYN_MOTOR_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };

    GPIO_PinInit(PIN_PILOT_SYN_MOTOR_GPIO, PIN_PILOT_SYN_MOTOR_PIN, &PILOT_SYN_MOTOR_config);
*/
    gpio_pin_config_t PILOT_EV_REGEN_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO3_12 (pin 38)  */
    GPIO_PinInit(PIN_PILOT_EV_REGEN_GPIO, PIN_PILOT_EV_REGEN_PIN, &PILOT_EV_REGEN_config);

    gpio_pin_config_t PILOT_EV_DISP_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO3_13 (pin 37)  */
    GPIO_PinInit(PIN_PILOT_EV_DISP_GPIO, PIN_PILOT_EV_DISP_PIN, &PILOT_EV_DISP_config);

    gpio_pin_config_t PILOT_EV_H2O_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO3_14 (pin 36)  */
    GPIO_PinInit(PIN_PILOT_EV_H2O_GPIO, PIN_PILOT_EV_H2O_PIN, &PILOT_EV_H2O_config);

    gpio_pin_config_t PILOT_DIVER_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO3_15 (pin 35)  */
    GPIO_PinInit(PIN_PILOT_DIVER_GPIO, PIN_PILOT_DIVER_PIN, &PILOT_DIVER_config);

    gpio_pin_config_t PUMP_SET_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO3_30 (pin 31)  */
    GPIO_PinInit(PIN_PUMP_SET_GPIO, PIN_PUMP_SET_PIN, &PUMP_SET_config);


    PORT0->PCR[0] = ((PORT0->PCR[0] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_MUX_MASK | PORT_PCR_IBE_MASK)))

                     /* Pin Multiplex Control: PORT0_0 (pin 49) is configured as SWDIO. */
                     | PORT_PCR_MUX(PORT0_PCR0_MUX_mux01)

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    PORT0->PCR[1] = ((PORT0->PCR[1] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_MUX_MASK | PORT_PCR_IBE_MASK)))

                     /* Pin Multiplex Control: PORT0_1 (pin 50) is configured as SWCLK. */
                     | PORT_PCR_MUX(PORT0_PCR1_MUX_mux01)

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT0_16 (pin 54) is configured as P0_16 */
    PORT_SetPinMux(PIN_ZC_IN_PORT, PIN_ZC_IN_PIN, kPORT_MuxAlt0);

    PORT0->PCR[16] = ((PORT0->PCR[16] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT0_17 (pin 55) is configured as P0_17 */
    PORT_SetPinMux(PIN_PILOT_GND_REL_HEAT_PORT, PIN_PILOT_GND_REL_HEAT_PIN, kPORT_MuxAlt0);

    PORT0->PCR[17] = ((PORT0->PCR[17] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT0_2 (pin 51) is configured as SWO */
    PORT_SetPinMux(PIN_TDO_SWO_PORT, PIN_TDO_SWO_PIN, kPORT_MuxAlt1);

    PORT0->PCR[2] = ((PORT0->PCR[2] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT0_3 (pin 52) is configured as TDI */
    PORT_SetPinMux(PIN_TDI_PORT, PIN_TDI_PIN, kPORT_MuxAlt1);

    PORT0->PCR[3] = ((PORT0->PCR[3] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT0_6 (pin 53) is configured as ADC0_A15 */
    PORT_SetPinMux(PIN_MEAS_3V3_PORT, PIN_MEAS_3V3_PIN, kPORT_MuxAlt0);

    PORT0->PCR[6] = ((PORT0->PCR[6] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Disables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe0));

    /* PORT1_0 (pin 56) is configured as P1_0 */
    PORT_SetPinMux(PIN_PILOT_GND_SWITCH_REL_PORT, PIN_PILOT_GND_SWITCH_REL_PIN, kPORT_MuxAlt0);

    PORT1->PCR[0] = ((PORT1->PCR[0] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT1_7 (pin 1) is configured as P1_7 */
    PORT_SetPinMux(PIN_FB_DIVER_PORT, PIN_FB_DIVER_PIN, kPORT_MuxAlt0);

    PORT1->PCR[7] = ((PORT1->PCR[7] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT1_2 (pin 58) is configured as ADC0_A18, CMP2_IN3 */
    PORT_SetPinMux(PIN_ADC0_A18_VBUS_DC_2_PORT, PIN_ADC0_A18_VBUS_DC_2_PIN, kPORT_MuxAlt0);

    PORT1->PCR[2] = ((PORT1->PCR[2] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Disables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe0));

    /* PORT1_3 (pin 59) is configured as ADC0_A19, CMP0_IN1 */
    PORT_SetPinMux(PIN_ADC0_A18_VBUS_DC_1_PORT, PIN_ADC0_A18_VBUS_DC_1_PIN, kPORT_MuxAlt0);

    PORT1->PCR[3] = ((PORT1->PCR[3] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Disables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe0));

    /* PORT1_30 (pin 9) is configured as XTAL48M */
    PORT_SetPinMux(PIN_OPT_XTAL_IN1_PORT, PIN_OPT_XTAL_IN1_PIN, kPORT_MuxAlt0);

    PORT1->PCR[30] = ((PORT1->PCR[30] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Disables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe0));

    /* PORT1_31 (pin 10) is configured as EXTAL48M */
    PORT_SetPinMux(PIN_OPT_XTAL_IN2_PORT, PIN_OPT_XTAL_IN2_PIN, kPORT_MuxAlt0);

    PORT1->PCR[31] = ((PORT1->PCR[31] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Disables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe0));

    /* PORT1_10 (pin 4) is configured as P1_10 */
    PORT_SetPinMux(PIN_FB_HEATER_PORT, PIN_FB_HEATER_PIN, kPORT_MuxAlt0);

    PORT1->PCR[10] = ((PORT1->PCR[10] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT2_0 (pin 14) is configured as OPAMP2_INP, ADC0_A0 */
    PORT_SetPinMux(PIN_OPAMP2_INP_GNDW_PORT, PIN_OPAMP2_INP_GNDW_PIN, kPORT_MuxAlt0);

    PORT2->PCR[0] = ((PORT2->PCR[0] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Disables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe0));

    /* PORT2_1 (pin 15) is configured as ADC1_A0, OPAMP2_INN */
    PORT_SetPinMux(PIN_ADC1_A0_CURR_W_PORT, PIN_ADC1_A0_CURR_W_PIN, kPORT_MuxAlt0);

    PORT2->PCR[1] = ((PORT2->PCR[1] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Disables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe0));

    /* PORT2_12 (pin 22) is configured as OPAMP0_INP */
    PORT_SetPinMux(PIN_OPAMP0_INP_GNDU_PORT, PIN_OPAMP0_INP_GNDU_PIN, kPORT_MuxAlt0);

    PORT2->PCR[12] = ((PORT2->PCR[12] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Disables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe0));

    /* PORT2_13 (pin 23) is configured as OPAMP0_INN */
    PORT_SetPinMux(PIN_OPAMP0_CURR_U_N_PORT, PIN_OPAMP0_CURR_U_N_PIN, kPORT_MuxAlt0);

    PORT2->PCR[13] = ((PORT2->PCR[13] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Disables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe0));

    /* PORT2_15 (pin 24) is configured as OPAMP0_OUT */
    PORT_SetPinMux(PIN_OPAMP0_OUT_CURR_U_PORT, PIN_OPAMP0_OUT_CURR_U_PIN, kPORT_MuxAlt0);

    PORT2->PCR[15] = ((PORT2->PCR[15] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Disables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe0));

    /* PORT2_16 (pin 25) is configured as OPAMP1_INP */
    PORT_SetPinMux(PIN_OPAMP1_INP_GNDV_PORT, PIN_OPAMP1_INP_GNDV_PIN, kPORT_MuxAlt0);

    PORT2->PCR[16] = ((PORT2->PCR[16] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Disables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe0));

    PORT2->PCR[17] = ((PORT2->PCR[17] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_MUX_MASK | PORT_PCR_IBE_MASK)))

                      /* Pin Multiplex Control: PORT2_17 (pin 26) is configured as OPAMP1_INN. */
                      | PORT_PCR_MUX(PORT2_PCR17_MUX_mux00)

                      /* Input Buffer Enable: Disables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe0));

    PORT2->PCR[19] = ((PORT2->PCR[19] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_MUX_MASK | PORT_PCR_IBE_MASK)))

                      /* Pin Multiplex Control: PORT2_19 (pin 27) is configured as OPAMP1_OUT. */
                      | PORT_PCR_MUX(PORT2_PCR19_MUX_mux00)

                      /* Input Buffer Enable: Disables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe0));

    PORT2->PCR[2] = ((PORT2->PCR[2] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_MUX_MASK | PORT_PCR_IBE_MASK)))

                     /* Pin Multiplex Control: PORT2_2 (pin 16) is configured as CMP0_IN0, ADC0_A4, DAC0_OUT. */
                     | PORT_PCR_MUX(PORT2_PCR2_MUX_mux00)

                     /* Input Buffer Enable: Disables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe0));

    /* PORT2_3 (pin 17) is configured as P2_3 */
    PORT_SetPinMux(PIN_IN_12V_DS_PORT, PIN_IN_12V_DS_PIN, kPORT_MuxAlt0);

    PORT2->PCR[3] = ((PORT2->PCR[3] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    PORT2->PCR[5] = ((PORT2->PCR[5] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_MUX_MASK | PORT_PCR_IBE_MASK)))

                     /* Pin Multiplex Control: PORT2_5 (pin 19) is configured as P2_5. */
                     | PORT_PCR_MUX(PORT2_PCR5_MUX_mux00)

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    PORT2->PCR[6] = ((PORT2->PCR[6] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_MUX_MASK | PORT_PCR_IBE_MASK)))

                     /* Pin Multiplex Control: PORT2_6 (pin 20) is configured as OPAMP2_OUT, ADC2_A2, ADC1_A3. */
                     | PORT_PCR_MUX(PORT2_PCR6_MUX_mux00)

                     /* Input Buffer Enable: Disables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe0));

    /* PORT2_7 (pin 21) is configured as ADC3_A7, ADC0_A7, ADC1_A7, VREFI, ADC2_A7 */
    PORT_SetPinMux(PIN_ADC0_VREF_IN_PORT, PIN_ADC0_VREF_IN_PIN, kPORT_MuxAlt0);

    PORT2->PCR[7] = ((PORT2->PCR[7] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Disables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe0));

    /* PORT3_0 (pin 46) is configured as PWM0_A0 */
    PORT_SetPinMux(PIN_PMW_U_H_PORT, PIN_PMW_U_H_PIN, kPORT_MuxAlt5);

    PORT3->PCR[0] = ((PORT3->PCR[0] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT3_1 (pin 45) is configured as PWM0_B0 */
    PORT_SetPinMux(PIN_PMW_U_L_PORT, PIN_PMW_U_L_PIN, kPORT_MuxAlt5);

    PORT3->PCR[1] = ((PORT3->PCR[1] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT3_10 (pin 40) is configured as PWM0_A2 */
    PORT_SetPinMux(PIN_PWM_W_H_PORT, PIN_PWM_W_H_PIN, kPORT_MuxAlt5);

    PORT3->PCR[10] = ((PORT3->PCR[10] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT3_11 (pin 39) is configured as PWM0_B2 */
    PORT_SetPinMux(PIN_PWM_W_L_PORT, PIN_PWM_W_L_PIN, kPORT_MuxAlt5);

    PORT3->PCR[11] = ((PORT3->PCR[11] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT3_12 (pin 38) is configured as P3_12 */
    PORT_SetPinMux(PIN_PILOT_EV_REGEN_PORT, PIN_PILOT_EV_REGEN_PIN, kPORT_MuxAlt0);

    PORT3->PCR[12] = ((PORT3->PCR[12] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT3_13 (pin 37) is configured as P3_13 */
    PORT_SetPinMux(PIN_PILOT_EV_DISP_PORT, PIN_PILOT_EV_DISP_PIN, kPORT_MuxAlt0);

    PORT3->PCR[13] = ((PORT3->PCR[13] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT3_14 (pin 36) is configured as P3_14 */
    PORT_SetPinMux(PIN_PILOT_EV_H2O_PORT, PIN_PILOT_EV_H2O_PIN, kPORT_MuxAlt0);

    PORT3->PCR[14] = ((PORT3->PCR[14] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT3_15 (pin 35) is configured as P3_15 */
    PORT_SetPinMux(PIN_PILOT_DIVER_PORT, PIN_PILOT_DIVER_PIN, kPORT_MuxAlt0);

    PORT3->PCR[15] = ((PORT3->PCR[15] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT3_27 (pin 34) is configured as LPUART4_TXD */
    PORT_SetPinMux(PIN_GEN_UART4_TX_PORT, PIN_GEN_UART4_TX_PIN, kPORT_MuxAlt3);

    PORT3->PCR[27] = ((PORT3->PCR[27] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT3_28 (pin 33) is configured as LPUART4_RXD */
    PORT_SetPinMux(PIN_GEN_UART4_RX_PORT, PIN_GEN_UART4_RX_PIN, kPORT_MuxAlt3);

    PORT3->PCR[28] = ((PORT3->PCR[28] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT3_30 (pin 31) is configured as P3_30 */
    PORT_SetPinMux(PIN_PUMP_SET_PORT, PIN_PUMP_SET_PIN, kPORT_MuxAlt0);

    PORT3->PCR[30] = ((PORT3->PCR[30] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT3_31 (pin 30) is configured as ADC1_A20 */
    PORT_SetPinMux(PIN_ADC1_A20_IPMTEMP_PORT, PIN_ADC1_A20_IPMTEMP_PIN, kPORT_MuxAlt0);

    PORT3->PCR[31] = ((PORT3->PCR[31] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Disables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe0));

    /* PORT3_7 (pin 43) is configured as P3_7 */

    PORT_SetPinMux(PIN_PILOT_SYN_MOTOR_PORT, PIN_PILOT_SYN_MOTOR_PIN, kPORT_MuxAlt0);

    PORT3->PCR[7] = ((PORT3->PCR[7] &

                      (~(PORT_PCR_IBE_MASK)))


                     | PORT_PCR_IBE(PCR_IBE_ibe1));


    /* PORT3_8 (pin 42) is configured as PWM0_A1 */
    PORT_SetPinMux(PIN_PWM_V_H_PORT, PIN_PWM_V_H_PIN, kPORT_MuxAlt5);

    PORT3->PCR[8] = ((PORT3->PCR[8] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT3_9 (pin 41) is configured as PWM0_B1 */
    PORT_SetPinMux(PIN_PWM_V_L_PORT, PIN_PWM_V_L_PIN, kPORT_MuxAlt5);

    PORT3->PCR[9] = ((PORT3->PCR[9] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
