/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define PCR_IBE_ibe0 0x00u          /*!<@brief Input Buffer Enable: Disables */
#define PCR_IBE_ibe1 0x01u          /*!<@brief Input Buffer Enable: Enables */
#define PORT0_PCR0_MUX_mux01 0x01u  /*!<@brief Pin Multiplex Control: Alternative 1 (chip-specific) */
#define PORT0_PCR1_MUX_mux01 0x01u  /*!<@brief Pin Multiplex Control: Alternative 1 (chip-specific) */
#define PORT2_PCR17_MUX_mux00 0x00u /*!<@brief Pin Multiplex Control: Alternative 0 (GPIO) */
#define PORT2_PCR19_MUX_mux00 0x00u /*!<@brief Pin Multiplex Control: Alternative 0 (GPIO) */
#define PORT2_PCR2_MUX_mux00 0x00u  /*!<@brief Pin Multiplex Control: Alternative 0 (GPIO) */
#define PORT2_PCR5_MUX_mux00 0x00u  /*!<@brief Pin Multiplex Control: Alternative 0 (GPIO) */
#define PORT2_PCR6_MUX_mux00 0x00u  /*!<@brief Pin Multiplex Control: Alternative 0 (GPIO) */

/*! @name PORT2_1 (number 15), OPAMP2_INN_CURR_W
  @{ */

/* Symbols to be used with PORT driver */
#define PIN_ADC1_A0_CURR_W_PORT PORT2               /*!<@brief PORT peripheral base pointer */
#define PIN_ADC1_A0_CURR_W_PIN 1U                   /*!<@brief PORT pin number */
#define PIN_ADC1_A0_CURR_W_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                    /* @} */

/*! @name PORT2_1 (number 15), OPAMP2_INN_CURR_W
  @{ */

/* Symbols to be used with PORT driver */
#define PIN_OPAMP2_INN_CURR_W_PORT PORT2               /*!<@brief PORT peripheral base pointer */
#define PIN_OPAMP2_INN_CURR_W_PIN 1U                   /*!<@brief PORT pin number */
#define PIN_OPAMP2_INN_CURR_W_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*! @name PORT2_2 (number 16), DAC_OUT
  @{ */

/* Symbols to be used with PORT driver */
#define PIN_DAC_OUT_PORT PORT2               /*!<@brief PORT peripheral base pointer */
#define PIN_DAC_OUT_PIN 2U                   /*!<@brief PORT pin number */
#define PIN_DAC_OUT_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                             /* @} */

/*! @name PORT2_7 (number 21), ADC_VREF_IN
  @{ */

/* Symbols to be used with PORT driver */
#define PIN_ADC0_VREF_IN_PORT PORT2               /*!<@brief PORT peripheral base pointer */
#define PIN_ADC0_VREF_IN_PIN 7U                   /*!<@brief PORT pin number */
#define PIN_ADC0_VREF_IN_PIN_MASK (1U << 7U)      /*!<@brief PORT pin mask */
                                                  /* @} */

/*! @name PORT2_7 (number 21), ADC_VREF_IN
  @{ */

/* Symbols to be used with PORT driver */
#define PIN_ADC2_VREF_IN_PORT PORT2               /*!<@brief PORT peripheral base pointer */
#define PIN_ADC2_VREF_IN_PIN 7U                   /*!<@brief PORT pin number */
#define PIN_ADC2_VREF_IN_PIN_MASK (1U << 7U)      /*!<@brief PORT pin mask */
                                                  /* @} */

/*! @name PORT2_7 (number 21), ADC_VREF_IN
  @{ */

/* Symbols to be used with PORT driver */
#define PIN_ADC3_VREF_IN_PORT PORT2               /*!<@brief PORT peripheral base pointer */
#define PIN_ADC3_VREF_IN_PIN 7U                   /*!<@brief PORT pin number */
#define PIN_ADC3_VREF_IN_PIN_MASK (1U << 7U)      /*!<@brief PORT pin mask */
                                                  /* @} */

/*! @name PORT2_7 (number 21), ADC_VREF_IN
  @{ */

/* Symbols to be used with PORT driver */
#define PIN_ADC1_VREF_IN_PORT PORT2               /*!<@brief PORT peripheral base pointer */
#define PIN_ADC1_VREF_IN_PIN 7U                   /*!<@brief PORT pin number */
#define PIN_ADC1_VREF_IN_PIN_MASK (1U << 7U)      /*!<@brief PORT pin mask */
                                                  /* @} */

/*! @name PORT2_7 (number 21), ADC_VREF_IN
  @{ */

/* Symbols to be used with PORT driver */
#define PIN_CMP0_VREF_IN_PORT PORT2               /*!<@brief PORT peripheral base pointer */
#define PIN_CMP0_VREF_IN_PIN 7U                   /*!<@brief PORT pin number */
#define PIN_CMP0_VREF_IN_PIN_MASK (1U << 7U)      /*!<@brief PORT pin mask */
                                                  /* @} */

/*! @name PORT2_7 (number 21), ADC_VREF_IN
  @{ */

/* Symbols to be used with PORT driver */
#define PIN_CMP1_VREF_IN_PORT PORT2               /*!<@brief PORT peripheral base pointer */
#define PIN_CMP1_VREF_IN_PIN 7U                   /*!<@brief PORT pin number */
#define PIN_CMP1_VREF_IN_PIN_MASK (1U << 7U)      /*!<@brief PORT pin mask */
                                                  /* @} */

/*! @name PORT2_7 (number 21), ADC_VREF_IN
  @{ */

/* Symbols to be used with PORT driver */
#define PIN_ADC2_A7_VREF_IN_PORT PORT2               /*!<@brief PORT peripheral base pointer */
#define PIN_ADC2_A7_VREF_IN_PIN 7U                   /*!<@brief PORT pin number */
#define PIN_ADC2_A7_VREF_IN_PIN_MASK (1U << 7U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PORT2_7 (number 21), ADC_VREF_IN
  @{ */

/* Symbols to be used with PORT driver */
#define PIN_ADC3_A7_VREF_IN_PORT PORT2               /*!<@brief PORT peripheral base pointer */
#define PIN_ADC3_A7_VREF_IN_PIN 7U                   /*!<@brief PORT pin number */
#define PIN_ADC3_A7_VREF_IN_PIN_MASK (1U << 7U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PORT2_7 (number 21), ADC_VREF_IN
  @{ */

/* Symbols to be used with PORT driver */
#define PIN_ADC0_A7_VREF_IN_PORT PORT2               /*!<@brief PORT peripheral base pointer */
#define PIN_ADC0_A7_VREF_IN_PIN 7U                   /*!<@brief PORT pin number */
#define PIN_ADC0_A7_VREF_IN_PIN_MASK (1U << 7U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PORT2_7 (number 21), ADC_VREF_IN
  @{ */

/* Symbols to be used with PORT driver */
#define PIN_ADC1_A7_VREF_IN_PORT PORT2               /*!<@brief PORT peripheral base pointer */
#define PIN_ADC1_A7_VREF_IN_PIN 7U                   /*!<@brief PORT pin number */
#define PIN_ADC1_A7_VREF_IN_PIN_MASK (1U << 7U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PORT2_13 (number 23), OPAMP0_CURR_U_N
  @{ */

/* Symbols to be used with PORT driver */
#define PIN_OPAMP0_CURR_U_N_PORT PORT2                /*!<@brief PORT peripheral base pointer */
#define PIN_OPAMP0_CURR_U_N_PIN 13U                   /*!<@brief PORT pin number */
#define PIN_OPAMP0_CURR_U_N_PIN_MASK (1U << 13U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PORT2_16 (number 25), OPAMP1_INP_GNDV
  @{ */

/* Symbols to be used with PORT driver */
#define PIN_OPAMP1_INP_GNDV_PORT PORT2                /*!<@brief PORT peripheral base pointer */
#define PIN_OPAMP1_INP_GNDV_PIN 16U                   /*!<@brief PORT pin number */
#define PIN_OPAMP1_INP_GNDV_PIN_MASK (1U << 16U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PORT3_31 (number 30), ADC1_IPMTEMP
  @{ */

/* Symbols to be used with PORT driver */
#define PIN_ADC1_A20_IPMTEMP_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define PIN_ADC1_A20_IPMTEMP_PIN 31U                   /*!<@brief PORT pin number */
#define PIN_ADC1_A20_IPMTEMP_PIN_MASK (1U << 31U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*! @name PORT3_31 (number 30), ADC1_IPMTEMP
  @{ */

/* Symbols to be used with PORT driver */
#define PIN_ADC1_A28_IPMTEMP_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define PIN_ADC1_A28_IPMTEMP_PIN 31U                   /*!<@brief PORT pin number */
#define PIN_ADC1_A28_IPMTEMP_PIN_MASK (1U << 31U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*! @name PORT3_30 (number 31), PUMP_SET
  @{ */

/* Symbols to be used with GPIO driver */
#define PIN_PUMP_SET_GPIO GPIO3                /*!<@brief GPIO peripheral base pointer */
#define PIN_PUMP_SET_GPIO_PIN 30U              /*!<@brief GPIO pin number */
#define PIN_PUMP_SET_GPIO_PIN_MASK (1U << 30U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define PIN_PUMP_SET_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define PIN_PUMP_SET_PIN 30U                   /*!<@brief PORT pin number */
#define PIN_PUMP_SET_PIN_MASK (1U << 30U)      /*!<@brief PORT pin mask */
                                               /* @} */

/*! @name PORT3_28 (number 33), GEN_UART4_RX
  @{ */

/* Symbols to be used with PORT driver */
#define PIN_GEN_UART4_RX_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define PIN_GEN_UART4_RX_PIN 28U                   /*!<@brief PORT pin number */
#define PIN_GEN_UART4_RX_PIN_MASK (1U << 28U)      /*!<@brief PORT pin mask */
                                                   /* @} */

/*! @name PORT3_27 (number 34), GEN_UART4_TX
  @{ */

/* Symbols to be used with PORT driver */
#define PIN_GEN_UART4_TX_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define PIN_GEN_UART4_TX_PIN 27U                   /*!<@brief PORT pin number */
#define PIN_GEN_UART4_TX_PIN_MASK (1U << 27U)      /*!<@brief PORT pin mask */
                                                   /* @} */

/*! @name PORT3_14 (number 36), PILOT_EV_H2O
  @{ */

/* Symbols to be used with GPIO driver */
#define PIN_PILOT_EV_H2O_GPIO GPIO3                /*!<@brief GPIO peripheral base pointer */
#define PIN_PILOT_EV_H2O_GPIO_PIN 14U              /*!<@brief GPIO pin number */
#define PIN_PILOT_EV_H2O_GPIO_PIN_MASK (1U << 14U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define PIN_PILOT_EV_H2O_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define PIN_PILOT_EV_H2O_PIN 14U                   /*!<@brief PORT pin number */
#define PIN_PILOT_EV_H2O_PIN_MASK (1U << 14U)      /*!<@brief PORT pin mask */
                                                   /* @} */

/*! @name PORT3_13 (number 37), PILOT_EV_DISP
  @{ */

/* Symbols to be used with GPIO driver */
#define PIN_PILOT_EV_DISP_GPIO GPIO3                /*!<@brief GPIO peripheral base pointer */
#define PIN_PILOT_EV_DISP_GPIO_PIN 13U              /*!<@brief GPIO pin number */
#define PIN_PILOT_EV_DISP_GPIO_PIN_MASK (1U << 13U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define PIN_PILOT_EV_DISP_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define PIN_PILOT_EV_DISP_PIN 13U                   /*!<@brief PORT pin number */
#define PIN_PILOT_EV_DISP_PIN_MASK (1U << 13U)      /*!<@brief PORT pin mask */
                                                    /* @} */

/*! @name PORT3_12 (number 38), PILOT_EV_REGEN
  @{ */

/* Symbols to be used with GPIO driver */
#define PIN_PILOT_EV_REGEN_GPIO GPIO3                /*!<@brief GPIO peripheral base pointer */
#define PIN_PILOT_EV_REGEN_GPIO_PIN 12U              /*!<@brief GPIO pin number */
#define PIN_PILOT_EV_REGEN_GPIO_PIN_MASK (1U << 12U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define PIN_PILOT_EV_REGEN_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define PIN_PILOT_EV_REGEN_PIN 12U                   /*!<@brief PORT pin number */
#define PIN_PILOT_EV_REGEN_PIN_MASK (1U << 12U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PORT3_9 (number 41), PWM_V_L
  @{ */

/* Symbols to be used with PORT driver */
#define PIN_PWM_V_L_PORT PORT3               /*!<@brief PORT peripheral base pointer */
#define PIN_PWM_V_L_PIN 9U                   /*!<@brief PORT pin number */
#define PIN_PWM_V_L_PIN_MASK (1U << 9U)      /*!<@brief PORT pin mask */
                                             /* @} */

/*! @name PORT3_8 (number 42), PWM_V_H
  @{ */

/* Symbols to be used with PORT driver */
#define PIN_PWM_V_H_PORT PORT3               /*!<@brief PORT peripheral base pointer */
#define PIN_PWM_V_H_PIN 8U                   /*!<@brief PORT pin number */
#define PIN_PWM_V_H_PIN_MASK (1U << 8U)      /*!<@brief PORT pin mask */
                                             /* @} */

/*! @name PORT3_1 (number 45), PMW_U_L
  @{ */

/* Symbols to be used with PORT driver */
#define PIN_PMW_U_L_PORT PORT3               /*!<@brief PORT peripheral base pointer */
#define PIN_PMW_U_L_PIN 1U                   /*!<@brief PORT pin number */
#define PIN_PMW_U_L_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                             /* @} */

/*! @name PORT3_0 (number 46), PMW_U_H
  @{ */

/* Symbols to be used with PORT driver */
#define PIN_PMW_U_H_PORT PORT3               /*!<@brief PORT peripheral base pointer */
#define PIN_PMW_U_H_PIN 0U                   /*!<@brief PORT pin number */
#define PIN_PMW_U_H_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                             /* @} */

/*! @name PORT0_1 (number 50), TCK_SWCLK
  @{ */

/* Symbols to be used with PORT driver */
#define PIN_TCK_SWCLK_PORT PORT0               /*!<@brief PORT peripheral base pointer */
#define PIN_TCK_SWCLK_PIN 1U                   /*!<@brief PORT pin number */
#define PIN_TCK_SWCLK_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                               /* @} */

/*! @name PORT1_2 (number 58), ADC0_A18_VBUS_DC_2
  @{ */

/* Symbols to be used with PORT driver */
#define PIN_ADC0_A18_VBUS_DC_2_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define PIN_ADC0_A18_VBUS_DC_2_PIN 2U                   /*!<@brief PORT pin number */
#define PIN_ADC0_A18_VBUS_DC_2_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PORT1_2 (number 58), ADC0_A18_VBUS_DC_2
  @{ */

/* Symbols to be used with PORT driver */
#define PIN_CMP2_IN3N_VBUS_DC_2_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define PIN_CMP2_IN3N_VBUS_DC_2_PIN 2U                   /*!<@brief PORT pin number */
#define PIN_CMP2_IN3N_VBUS_DC_2_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORT1_2 (number 58), ADC0_A18_VBUS_DC_2
  @{ */

/* Symbols to be used with PORT driver */
#define PIN_CMP2_IN3P_VBUS_DC_2_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define PIN_CMP2_IN3P_VBUS_DC_2_PIN 2U                   /*!<@brief PORT pin number */
#define PIN_CMP2_IN3P_VBUS_DC_2_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORT1_3 (number 59), ADC0_A18_VBUS_DC_1
  @{ */

/* Symbols to be used with PORT driver */
#define PIN_ADC0_A18_VBUS_DC_1_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define PIN_ADC0_A18_VBUS_DC_1_PIN 3U                   /*!<@brief PORT pin number */
#define PIN_ADC0_A18_VBUS_DC_1_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PORT1_3 (number 59), ADC0_A18_VBUS_DC_1
  @{ */

/* Symbols to be used with PORT driver */
#define PIN_CMP0_IN1P_VBUS_DC_1_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define PIN_CMP0_IN1P_VBUS_DC_1_PIN 3U                   /*!<@brief PORT pin number */
#define PIN_CMP0_IN1P_VBUS_DC_1_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORT1_3 (number 59), ADC0_A18_VBUS_DC_1
  @{ */

/* Symbols to be used with PORT driver */
#define PIN_CMP0_IN1N_VBUS_DC_1_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define PIN_CMP0_IN1N_VBUS_DC_1_PIN 3U                   /*!<@brief PORT pin number */
#define PIN_CMP0_IN1N_VBUS_DC_1_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORT0_0 (number 49), TMS_SWDIO
  @{ */

/* Symbols to be used with PORT driver */
#define PIN_TMS_SWDIO_PORT PORT0               /*!<@brief PORT peripheral base pointer */
#define PIN_TMS_SWDIO_PIN 0U                   /*!<@brief PORT pin number */
#define PIN_TMS_SWDIO_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                               /* @} */

/*! @name PORT0_2 (number 51), TDO_SWO
  @{ */

/* Symbols to be used with PORT driver */
#define PIN_TDO_SWO_PORT PORT0               /*!<@brief PORT peripheral base pointer */
#define PIN_TDO_SWO_PIN 2U                   /*!<@brief PORT pin number */
#define PIN_TDO_SWO_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                             /* @} */

/*! @name PORT1_31 (number 10), OPT_XTAL_IN2
  @{ */

/* Symbols to be used with PORT driver */
#define PIN_OPT_XTAL_IN2_PORT PORT1                /*!<@brief PORT peripheral base pointer */
#define PIN_OPT_XTAL_IN2_PIN 31U                   /*!<@brief PORT pin number */
#define PIN_OPT_XTAL_IN2_PIN_MASK (1U << 31U)      /*!<@brief PORT pin mask */
                                                   /* @} */

/*! @name PORT2_3 (number 17), IN_12V_DS
  @{ */

/* Symbols to be used with GPIO driver */
#define PIN_IN_12V_DS_GPIO GPIO2               /*!<@brief GPIO peripheral base pointer */
#define PIN_IN_12V_DS_GPIO_PIN 3U              /*!<@brief GPIO pin number */
#define PIN_IN_12V_DS_GPIO_PIN_MASK (1U << 3U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define PIN_IN_12V_DS_PORT PORT2               /*!<@brief PORT peripheral base pointer */
#define PIN_IN_12V_DS_PIN 3U                   /*!<@brief PORT pin number */
#define PIN_IN_12V_DS_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                               /* @} */

/*! @name PORT1_0 (number 56), PILOT_GND_SWITCH_REL
  @{ */

/* Symbols to be used with GPIO driver */
#define PIN_PILOT_GND_SWITCH_REL_GPIO GPIO1               /*!<@brief GPIO peripheral base pointer */
#define PIN_PILOT_GND_SWITCH_REL_GPIO_PIN 0U              /*!<@brief GPIO pin number */
#define PIN_PILOT_GND_SWITCH_REL_GPIO_PIN_MASK (1U << 0U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define PIN_PILOT_GND_SWITCH_REL_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define PIN_PILOT_GND_SWITCH_REL_PIN 0U                   /*!<@brief PORT pin number */
#define PIN_PILOT_GND_SWITCH_REL_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PORT3_11 (number 39), PWM_W_L
  @{ */

/* Symbols to be used with PORT driver */
#define PIN_PWM_W_L_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define PIN_PWM_W_L_PIN 11U                   /*!<@brief PORT pin number */
#define PIN_PWM_W_L_PIN_MASK (1U << 11U)      /*!<@brief PORT pin mask */
                                              /* @} */

/*! @name PORT3_10 (number 40), PWM_W_H
  @{ */

/* Symbols to be used with PORT driver */
#define PIN_PWM_W_H_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define PIN_PWM_W_H_PIN 10U                   /*!<@brief PORT pin number */
#define PIN_PWM_W_H_PIN_MASK (1U << 10U)      /*!<@brief PORT pin mask */
                                              /* @} */

/*! @name PORT2_12 (number 22), OPAMP0_INP_GNDU
  @{ */

/* Symbols to be used with PORT driver */
#define PIN_OPAMP0_INP_GNDU_PORT PORT2                /*!<@brief PORT peripheral base pointer */
#define PIN_OPAMP0_INP_GNDU_PIN 12U                   /*!<@brief PORT pin number */
#define PIN_OPAMP0_INP_GNDU_PIN_MASK (1U << 12U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PORT0_16 (number 54), ZC_IN
  @{ */

/* Symbols to be used with GPIO driver */
#define PIN_ZC_IN_GPIO GPIO0                /*!<@brief GPIO peripheral base pointer */
#define PIN_ZC_IN_GPIO_PIN 16U              /*!<@brief GPIO pin number */
#define PIN_ZC_IN_GPIO_PIN_MASK (1U << 16U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define PIN_ZC_IN_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define PIN_ZC_IN_PIN 16U                   /*!<@brief PORT pin number */
#define PIN_ZC_IN_PIN_MASK (1U << 16U)      /*!<@brief PORT pin mask */
                                            /* @} */

/*! @name PORT0_17 (number 55), PILOT_GND_REL_HEAT
  @{ */

/* Symbols to be used with GPIO driver */
#define PIN_PILOT_GND_REL_HEAT_GPIO GPIO0                /*!<@brief GPIO peripheral base pointer */
#define PIN_PILOT_GND_REL_HEAT_GPIO_PIN 17U              /*!<@brief GPIO pin number */
#define PIN_PILOT_GND_REL_HEAT_GPIO_PIN_MASK (1U << 17U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define PIN_PILOT_GND_REL_HEAT_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define PIN_PILOT_GND_REL_HEAT_PIN 17U                   /*!<@brief PORT pin number */
#define PIN_PILOT_GND_REL_HEAT_PIN_MASK (1U << 17U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORT2_19 (number 27), OPAMP1_OUT_CURR_V
  @{ */

/* Symbols to be used with PORT driver */
#define PIN_OPAMP1_OUT_CURR_V_PORT PORT2                /*!<@brief PORT peripheral base pointer */
#define PIN_OPAMP1_OUT_CURR_V_PIN 19U                   /*!<@brief PORT pin number */
#define PIN_OPAMP1_OUT_CURR_V_PIN_MASK (1U << 19U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PORT2_15 (number 24), OPAMP0_OUT_CURR_U
  @{ */

/* Symbols to be used with PORT driver */
#define PIN_OPAMP0_OUT_CURR_U_PORT PORT2                /*!<@brief PORT peripheral base pointer */
#define PIN_OPAMP0_OUT_CURR_U_PIN 15U                   /*!<@brief PORT pin number */
#define PIN_OPAMP0_OUT_CURR_U_PIN_MASK (1U << 15U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PORT2_17 (number 26), OPAMP1_INN_CURR_V
  @{ */

/* Symbols to be used with PORT driver */
#define PIN_OPAMP1_INN_CURR_V_PORT PORT2                /*!<@brief PORT peripheral base pointer */
#define PIN_OPAMP1_INN_CURR_V_PIN 17U                   /*!<@brief PORT pin number */
#define PIN_OPAMP1_INN_CURR_V_PIN_MASK (1U << 17U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PORT2_0 (number 14), OPAMP2_INP_GNDW
  @{ */

/* Symbols to be used with PORT driver */
#define PIN_OPAMP2_INP_GNDW_PORT PORT2               /*!<@brief PORT peripheral base pointer */
#define PIN_OPAMP2_INP_GNDW_PIN 0U                   /*!<@brief PORT pin number */
#define PIN_OPAMP2_INP_GNDW_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PORT2_0 (number 14), OPAMP2_INP_GNDW
  @{ */

/* Symbols to be used with PORT driver */
#define PIN_ADC0_A0_GNDW_PORT PORT2               /*!<@brief PORT peripheral base pointer */
#define PIN_ADC0_A0_GNDW_PIN 0U                   /*!<@brief PORT pin number */
#define PIN_ADC0_A0_GNDW_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                  /* @} */

/*! @name PORT2_6 (number 20), OPAMP2_OUT_CURR_W
  @{ */

/* Symbols to be used with PORT driver */
#define PIN_OPAMP2_OUT_CURR_W_PORT PORT2               /*!<@brief PORT peripheral base pointer */
#define PIN_OPAMP2_OUT_CURR_W_PIN 6U                   /*!<@brief PORT pin number */
#define PIN_OPAMP2_OUT_CURR_W_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*! @name PORT2_6 (number 20), OPAMP2_OUT_CURR_W
  @{ */

/* Symbols to be used with PORT driver */
#define PIN_ADC2_A2_CURR_W_PORT PORT2               /*!<@brief PORT peripheral base pointer */
#define PIN_ADC2_A2_CURR_W_PIN 6U                   /*!<@brief PORT pin number */
#define PIN_ADC2_A2_CURR_W_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                                    /* @} */

/*! @name PORT2_6 (number 20), OPAMP2_OUT_CURR_W
  @{ */

/* Symbols to be used with PORT driver */
#define PIN_ADC1_A3_CURR_W_PORT PORT2               /*!<@brief PORT peripheral base pointer */
#define PIN_ADC1_A3_CURR_W_PIN 6U                   /*!<@brief PORT pin number */
#define PIN_ADC1_A3_CURR_W_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                                    /* @} */

/*! @name PORT1_30 (number 9), OPT_XTAL_IN1
  @{ */

/* Symbols to be used with PORT driver */
#define PIN_OPT_XTAL_IN1_PORT PORT1                /*!<@brief PORT peripheral base pointer */
#define PIN_OPT_XTAL_IN1_PIN 30U                   /*!<@brief PORT pin number */
#define PIN_OPT_XTAL_IN1_PIN_MASK (1U << 30U)      /*!<@brief PORT pin mask */
                                                   /* @} */

/*! @name PORT2_5 (number 19), PILOT_FAIL_TST_BULK
  @{ */

/* Symbols to be used with GPIO driver */
#define PIN_PILOT_FAIL_TST_BULK_GPIO GPIO2               /*!<@brief GPIO peripheral base pointer */
#define PIN_PILOT_FAIL_TST_BULK_GPIO_PIN 5U              /*!<@brief GPIO pin number */
#define PIN_PILOT_FAIL_TST_BULK_GPIO_PIN_MASK (1U << 5U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define PIN_PILOT_FAIL_TST_BULK_PORT PORT2               /*!<@brief PORT peripheral base pointer */
#define PIN_PILOT_FAIL_TST_BULK_PIN 5U                   /*!<@brief PORT pin number */
#define PIN_PILOT_FAIL_TST_BULK_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORT1_11 (number 5), FB_DIVER
  @{ */

/* Symbols to be used with GPIO driver */
#define PIN_FB_DIVER_GPIO GPIO1                /*!<@brief GPIO peripheral base pointer */
#define PIN_FB_DIVER_GPIO_PIN 7U              /*!<@brief GPIO pin number */
#define PIN_FB_DIVER_GPIO_PIN_MASK (1U << 7U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define PIN_FB_DIVER_PORT PORT1                /*!<@brief PORT peripheral base pointer */
#define PIN_FB_DIVER_PIN 7U                   /*!<@brief PORT pin number */
#define PIN_FB_DIVER_PIN_MASK (1U << 7U)      /*!<@brief PORT pin mask */
                                               /* @} */

/*! @name RESET_B (number 8), RESET
  @{ */
/* @} */

/*! @name PORT1_9 (number 3), FB_HEATER
  @{ */

/* Symbols to be used with GPIO driver */
#define PIN_FB_HEATER_GPIO GPIO1               /*!<@brief GPIO peripheral base pointer */
#define PIN_FB_HEATER_GPIO_PIN 10U              /*!<@brief GPIO pin number */
#define PIN_FB_HEATER_GPIO_PIN_MASK (1U << 10U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define PIN_FB_HEATER_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define PIN_FB_HEATER_PIN 10U                   /*!<@brief PORT pin number */
#define PIN_FB_HEATER_PIN_MASK (1U << 10U)      /*!<@brief PORT pin mask */
                                               /* @} */

/*! @name PORT2_2 (number 16), DAC_OUT
  @{ */

/* Symbols to be used with PORT driver */
#define PIN_DAC_OUT_CMP0N_PORT PORT2               /*!<@brief PORT peripheral base pointer */
#define PIN_DAC_OUT_CMP0N_PIN 2U                   /*!<@brief PORT pin number */
#define PIN_DAC_OUT_CMP0N_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                   /* @} */

/*! @name PORT2_2 (number 16), DAC_OUT
  @{ */

/* Symbols to be used with PORT driver */
#define PIN_DAC_OUT_CMP0P_PORT PORT2               /*!<@brief PORT peripheral base pointer */
#define PIN_DAC_OUT_CMP0P_PIN 2U                   /*!<@brief PORT pin number */
#define PIN_DAC_OUT_CMP0P_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                   /* @} */

/*! @name PORT2_2 (number 16), DAC_OUT
  @{ */

/* Symbols to be used with PORT driver */
#define PIN_DAC_OUT_ADC0A4_PORT PORT2               /*!<@brief PORT peripheral base pointer */
#define PIN_DAC_OUT_ADC0A4_PIN 2U                   /*!<@brief PORT pin number */
#define PIN_DAC_OUT_ADC0A4_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                    /* @} */

/*! @name PORT3_15 (number 35), PILOT_DIVER
  @{ */

/* Symbols to be used with GPIO driver */
#define PIN_PILOT_DIVER_GPIO GPIO3                /*!<@brief GPIO peripheral base pointer */
#define PIN_PILOT_DIVER_GPIO_PIN 15U              /*!<@brief GPIO pin number */
#define PIN_PILOT_DIVER_GPIO_PIN_MASK (1U << 15U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define PIN_PILOT_DIVER_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define PIN_PILOT_DIVER_PIN 15U                   /*!<@brief PORT pin number */
#define PIN_PILOT_DIVER_PIN_MASK (1U << 15U)      /*!<@brief PORT pin mask */
                                                  /* @} */

/*! @name PORT3_7 (number 43), PILOT_SYN_MOTOR
  @{ */

/* Symbols to be used with GPIO driver */
#define PIN_PILOT_SYN_MOTOR_GPIO GPIO3               /*!<@brief GPIO peripheral base pointer */
#define PIN_PILOT_SYN_MOTOR_GPIO_PIN 7U              /*!<@brief GPIO pin number */
#define PIN_PILOT_SYN_MOTOR_GPIO_PIN_MASK (1U << 7U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define PIN_PILOT_SYN_MOTOR_PORT PORT3               /*!<@brief PORT peripheral base pointer */
#define PIN_PILOT_SYN_MOTOR_PIN 7U                   /*!<@brief PORT pin number */
#define PIN_PILOT_SYN_MOTOR_PIN_MASK (1U << 7U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PORT0_3 (number 52), TDI
  @{ */

/* Symbols to be used with PORT driver */
#define PIN_TDI_PORT PORT0               /*!<@brief PORT peripheral base pointer */
#define PIN_TDI_PIN 3U                   /*!<@brief PORT pin number */
#define PIN_TDI_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                         /* @} */

/*! @name PORT0_6 (number 53), MEAS_3V3
  @{ */

/* Symbols to be used with PORT driver */
#define PIN_MEAS_3V3_PORT PORT0               /*!<@brief PORT peripheral base pointer */
#define PIN_MEAS_3V3_PIN 6U                   /*!<@brief PORT pin number */
#define PIN_MEAS_3V3_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                              /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
