#ifndef APP_CONFIG_H
#define APP_CONFIG_H

#include "env.h"

/* #define ENABLE_WM_APPLICATION */
/* #define ENABLE_DRYER_APPLICATION */
/* #define ENABLE_AIRCON_APPLICATION */
/* #define ENABLE_REFRIGERATOR_APPLICATION */
#define ENABLE_DISHWASHER_APPLICATION

#ifdef ENABLE_WM_APPLICATION
#define ENABLE_WM_APPLICATION_AVKp
/* #define ENABLE_WM_APPLICATION_SONIC */
#elif defined(ENABLE_DRYER_APPLICATION)
#define ENABLE_DRYER_APPLICATION_AVKp
/* #define ENABLE_DRYER_APPLICATION_SONIC */
#elif defined(ENABLE_AIRCON_APPLICATION)
#define ENABLE_APOS
#endif

#endif
